<div class="content post-detail"
     data-url="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
     data-title="<?php echo $this->arrContent['cont_title'] ?>" data-id="<?php echo $this->arrContent['cont_id'] ?>"
     data-load="true">
    <h1>
        <span itemprop="name"><?php echo $this->arrContent['cont_title']; ?></span>
    </h1>
    <div class="socialbox top clearfix">
        <ul>
            <li class="views"><?php echo number_format($this->arrContent['cont_views'] + 1, 0, ",", "."); ?></li>
            <li class="share">
                <div class="sharebox">
                    <div class="sharetoolbox">
                        <div class="g-plusone" data-annotation="none" data-size="medium"
                             data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]); ?>"></div>

                        <div class="fb-like"
                             data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]); ?>"
                             data-layout="button_count" data-action="like" data-show-faces="false"
                             data-share="true"></div>
                        <div class="fb-like likebox" data-href="<?php echo \My\General::SOCIAL_FACEBOOK_URL; ?>"
                             data-layout="button_count" data-action="like" data-show-faces="false"
                             data-share="false"></div>
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <div class="breadcrumbs info-detail" xmlns:v="http://rdf.data-vocabulary.org/#">
        <span class="first breadcrumb">
            <a href="<?php echo BASE_URL; ?>">🏠</a>
        </span>
        <?php if (!empty($this->arrCategoryParent)): ?>
            <span itemprop="articleSection" typeof="v:Breadcrumb" class="breadcrumb">
                    <a rel="v:url" property="v:title"
                       href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryParent['cate_slug'], 'cateId' => $this->arrCategoryParent['cate_id']]) ?>">
                        <?php echo $this->arrCategoryParent['cate_name']; ?>
                    </a>
                </span>
        <?php endif; ?>
        <span itemprop="articleSection" typeof="v:Breadcrumb" class="breadcrumb">
            <a rel="v:url" property="v:title"
               href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id']]) ?>">
                <?php echo $this->arrCategoryDetail['cate_name']; ?>
            </a>
        </span>
    </div>

    <div class="content-detail">
        <div id="adsarticletop" class="adbox">
            <!-- khampha content -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-9166980393030854"
                 data-ad-slot="3530466045"
                 data-ad-format="auto"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
        <?php echo in_array($this->arrContent['cate_id'], \My\General::$cate_videos) ? '<p>' . $this->arrContent['cont_detail'] . '</p>' : $this->arrContent['cont_detail']; ?>
        <?php if (in_array($this->arrContent['cate_id'], \My\General::$cate_videos)): ?>
            <iframe width="700" height="400"
                    src="https://www.youtube.com/embed/<?php echo $this->arrContent['from_source'] ?>" frameborder="0"
                    allowfullscreen></iframe>
        <?php endif; ?>
    </div>
    <div class="author-info clearfix">
        <span class="date">Cập nhật: <?php echo date('d/m/Y', $this->arrContent['updated_date']) ?></span>
        <span class="author" style="float: right">
        <?php echo in_array($this->arrContent['cate_id'], \My\General::$cate_videos) ? 'YouTube' : (empty($this->arrContent['cont_detail_text']) ? 'Tổng hợp' : $this->arrContent['cont_detail_text']) ?>
        </span>
    </div>
    <div id="adsarticletop" class="adbox">
        <!-- khampha content -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-9166980393030854"
             data-ad-slot="3530466045"
             data-ad-format="auto"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
    <div class="tags">
        <span><b>Xem thêm:</b></span>
        <?php if (!empty($this->arrKeywordList)):
            foreach ($this->arrKeywordList as $arr_key):
                ?>
                <a href="<?php echo $this->serverUrl() . $this->Url('keyword', array('keySlug' => $arr_key['key_slug'], 'keyId' => $arr_key['key_id'])) ?>"><?php echo $arr_key['key_name']; ?></a>
                <?php
            endforeach;
        endif; ?>
    </div>

    <div class="listitems">
        <div class="title">Tham khảo thêm</div>
        <ul>
            <?php if (!empty($this->arrContentLikeList)):
                foreach ($this->arrContentLikeList as $arr_content):
                    ?>
                    <li>
                        <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>">
                            <?php echo $arr_content['cont_title']; ?>
                            <span>
                                <?php echo number_format($arr_content['cont_views'], 0, ",", "."); ?>
                                người xem
                            </span>
                            <?php echo in_array($arr_content['cate_id'], \My\General::$cate_videos) ? '<img src ="' . STATIC_URL . '/f/v1/images/video_icon-sm.png" title="videos"/>' : '' ?>
                        </a>
                    </li>
                <?php endforeach;
            endif;
            ?>
        </ul>
    </div>

    <!--    <div id="adsarticlebottom" class="adbox">-->
    <!--        <ins class="adsbygoogle"-->
    <!--             style="display:inline-block;width:728px;height:90px"-->
    <!--             data-ad-client="ca-pub-4608570842050780"-->
    <!--             data-ad-slot="5752635152"></ins>-->
    <!--        <script>-->
    <!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
    <!--        </script>-->
    <!--    </div>-->
    <div class="socialbox bottom clearfix">
        <ul>
            <li class="share">
                <div class="sharebox">
                    <div class="sharetoolbox">
                        <div class="g-plusone" data-annotation="none" data-size="medium"
                             data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"></div>

                        <div class="fb-like"
                             data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
                             data-layout="button_count" data-action="like" data-show-faces="false"
                             data-share="true"></div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <p>
        <a href="<?php echo \My\General::SOCIAL_FACEBOOK_URL; ?>" target="_blank" rel="nofollow">Theo dõi cộng đồng
            <?php echo \My\General::SITE_AUTH; ?> trên
            facebook</a>
    </p>
    <div class="fb-like" data-href="<?php echo \My\General::SOCIAL_FACEBOOK_URL; ?>" data-layout="standard"
         data-action="recommend" data-show-faces="true" data-share="true"></div>

    <div class="comments">
        <div id="fb_comments" class="fb-comments"
             data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
             data-num-posts="3"
             data-width="640"></div>
    </div>
    <!--    <div id="suggestion" class="adbox">-->
    <!--        <ins class="adsbygoogle"-->
    <!--             style="display:inline-block;width:728px;height:90px"-->
    <!--             data-ad-client="ca-pub-4608570842050780"-->
    <!--             data-ad-slot="5752635152"></ins>-->
    <!--        <script>-->
    <!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
    <!--        </script>-->
    <!--    </div>-->

    <div class="more-news latest">
        <div class="list-title">Bài viết mới nhất</div>
        <ul class="clearfix">
            <?php foreach ($this->arrContentNews as $arr_content):
                ?>
                <li>
                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>">
                        <span class="thumb-detail">
                            <img src="<?php echo $arr_content['cont_main_image'] ?>"
                                 alt="<?php echo $arr_content['cont_title'] ?>"/>
                        </span>
                        <span><?php echo $arr_content['cont_title'] ?></span>
                        <?php echo in_array($arr_content['cate_id'], \My\General::$cate_videos) ? '<img src ="' . STATIC_URL . '/f/v1/images/video_icon-sm.png" title="videos"/>' : '' ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
        <?php if (!empty($this->arrCategoryParent)): ?>
            <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryParent['cate_slug'], 'cateId' => $this->arrCategoryParent['cate_id']]) ?>"
               class="viewmore"><b>Xem thêm</b> <?php echo $this->arrCategoryParent['cate_name']; ?></a>
        <?php endif; ?>
    </div>

    <div class="more-news">
        <div class="list-title">Bài viết <?php echo $this->arrCategoryDetail['cate_name']; ?> khác</div>
        <ul class="clearfix">
            <?php
            if (!empty($this->arrContentLastedList)):
                foreach ($this->arrContentLastedList as $arr_content):
                    ?>
                    <li>
                        <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>">
                        <span class="thumb-detail">
                            <img src="<?php echo $arr_content['cont_main_image'] ?>"
                                 alt="<?php echo $arr_content['cont_title'] ?>"/>
                        </span>
                            <span><?php echo $arr_content['cont_title'] ?></span>
                            <?php echo in_array($arr_content['cate_id'], \My\General::$cate_videos) ? '<img src ="' . STATIC_URL . '/f/v1/images/video_icon-sm.png" title="videos"/>' : '' ?>
                        </a>
                    </li>
                <?php endforeach;
            endif;
            ?>
        </ul>
        <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id']]) ?>"
           class="viewmore">Xem thêm</a>
    </div>
</div>
<script type="application/ld+json">
    {
    "@context": "http://schema.org",
    "@type": "NewsArticle",
    "mainEntityOfPage":{
    "@type":"WebPage",
    "@id":"<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
    },
    "headline": "<?php echo $this->metaTitle; ?>",
    "image": {
    "@type": "ImageObject",
    "url": "<?php echo $this->arrContent['cont_main_image'] ?>",
    "height": 800,
    "width": 800
    },
    "datePublished": "<?php echo date('Y/m/d', $this->arrContent['created_date']); ?>",
    "dateModified": "<?php echo date('Y/m/d', $this->arrContent['created_date']); ?>",
    "author": {
    "@type": "Person",
    "name": "<?php echo in_array($this->arrContent['cate_id'], \My\General::$cate_videos) ? 'YouTube' : (empty($this->arrContent['cont_detail_text']) ? 'Tổng hợp' : $this->arrContent['cont_detail_text']) ?>"
    },
    "publisher": {
    "@type": "Organization",
    "name": "<?php echo $this->metaTitle; ?>",
    "logo": {
    "@type": "ImageObject",
    "url": "<?php echo $this->arrContent['cont_main_image'] ?>",
    "width": 600,
    "height": 60
    }
    },
    "description": "<?php echo $this->metaDescription ?>"
    }



















































</script>