<?php
$arr_content_detail = $this->arrContent;
$cont_detail_image = $this->cont_detail_image;
$url_video = 'https://www.youtube.com/watch?v=' . $arr_content_detail['from_source'];
?>
<div id="view-page">
    <div class="container page-width">
        <div class="main-content">
            <div style="display: block;" class="post" video-index="0">
                <div class="header">
                    <div class="line-style line-start"></div>
                    <video
                        id="vid1"
                        class="video-js vjs-default-skin vjs-16-9 vjs-big-play-centered"
                        controls
                        poster="<?php echo $cont_detail_image['640x480'] ?>"
                        data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "<?php echo $url_video; ?>"}], "youtube": { "iv_load_policy": 1 } }'
                    >
                    </video>
                    <!--                    autoplay-->
                    <div class="line-style line-end">
                        <a href="javascript:;" class="btn btn-share"
                           onclick="ViewPage.btnShare(this); return false;"
                        >
                            <span class="icon"></span>Share now
                        </a>
                        <div class="social">
                            <a href="javascript:;" data-title="<?php echo $arr_content_detail['cont_title']; ?>"
                               data-url="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content_detail['cont_slug'], 'contentId' => $arr_content_detail['cont_id']]); ?>"
                               onclick="ViewPage.shareSocial(this, 'facebook'); return false;" class="facebook">
                            </a>
                            <a href="javascript:;" data-title="<?php echo $arr_content_detail['cont_title']; ?>"
                               data-url="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content_detail['cont_slug'], 'contentId' => $arr_content_detail['cont_id']]); ?>"
                               onclick="ViewPage.shareSocial(this, 'google'); return false;" class="google">
                            </a>
                            <a href="#" data-title="<?php echo $arr_content_detail['cont_title']; ?>"
                               data-url="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content_detail['cont_slug'], 'contentId' => $arr_content_detail['cont_id']]); ?>"
                               onclick="ViewPage.shareSocial(this, 'twitter'); return false;" class="twitter">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="content">
                    <h1 class="title"><?php echo $arr_content_detail['cont_title']; ?></h1>
                    <div class="score-container">
                        <div id="like-276" class="like" data-text="276">
                            <!-- add class active -->
                            <a href="#" class="btn btn-like">
                                <div class="sharetoolbox">
                                    <div class="g-plusone" data-annotation="none" data-size="medium"
                                         data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content_detail['cont_slug'], 'contentId' => $arr_content_detail['cont_id']]); ?>"></div>
                                    <div class="fb-like"
                                         data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content_detail['cont_slug'], 'contentId' => $arr_content_detail['cont_id']]); ?>"
                                         data-layout="button_count" data-action="like" data-show-faces="false"
                                         data-share="true">
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="hot">
                            <p class="hide">
                                <span
                                    class="score"><?php echo number_format($arr_content_detail['cont_views']); ?></span>
                                View
                            </p>
                        </div>
                    </div>
                    <div class="readMore-container">
                        <div class="description-container">
                            <p class="title">Description:</p>
                            <p class="description">
                                <?php echo $arr_content_detail['cont_description']; ?>
                            </p>
                        </div>
                        <div class="share">
                            <p class="title">Share :</p>
                            <div class="social">
                                <a href="#" data-title="<?php echo $arr_content_detail['cont_title']; ?>"
                                   data-url="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content_detail['cont_slug'], 'contentId' => $arr_content_detail['cont_id']]); ?>"
                                   onclick="ViewPage.shareSocial(this, 'facebook'); return false;" class="facebook">
                                </a>
                                <a href="#" data-title="<?php echo $arr_content_detail['cont_title']; ?>"
                                   data-url="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content_detail['cont_slug'], 'contentId' => $arr_content_detail['cont_id']]); ?>"
                                   onclick="ViewPage.shareSocial(this, 'google'); return false;" class="google">
                                </a>
                                <a href="#" data-title="<?php echo $arr_content_detail['cont_title']; ?>"
                                   data-url="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content_detail['cont_slug'], 'contentId' => $arr_content_detail['cont_id']]); ?>"
                                   onclick="ViewPage.shareSocial(this, 'twitter'); return false;" class="twitter">
                                </a>
                            </div>
                        </div>

                        <div class="cmt-form" data-text="276">
                            <div id="fb_comments" class="fb-comments"
                                 data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
                                 data-num-posts="3"
                                 data-width="640">
                            </div>
                        </div>
                        <?php if (!empty($this->arrTagList)): ?>
                            <div class="tags">
                                <p class="title">Tags:</p>
                                <ul>
                                    <?php foreach ($this->arrTagList as $tag): ?>
                                        <li>
                                            <a href="<?php echo $this->Url('tag', array('tagSlug' => $tag['tag_slug'], 'tagId' => $tag['tag_id'])) ?>"
                                               title="<?php echo $tag['tag_name']; ?>">
                                                <?php echo $tag['tag_name']; ?>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>

                                </ul>
                            </div>
                        <?php endif; ?>

                        <?php if (!empty($this->arrKeywordList)): ?>
                            <div class="tags">
                                <p class="title">Keywords:</p>
                                <ul>
                                    <?php foreach ($this->arrKeywordList as $arr_key): ?>
                                        <li>
                                            <a href="<?php echo $this->Url('keyword', array('keySlug' => $arr_key['key_slug'], 'keyId' => $arr_key['key_id'])) ?>"
                                               title="<?php echo $arr_key['key_name']; ?>">
                                                <?php echo $arr_key['key_name']; ?>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="sidebar" style="position: absolute; top: 0px; right: 20px; bottom: auto;">
            <div class="sidebar-ads">
                <!--                <ins data-revive-zoneid="3" data-revive-id="483fea3690ccb88311197e30f6264e09" id="revive-0-1"></ins>-->
                <!--                <script async="" src="http://ads.thatvidieu.com/delivery/asyncjs.php"></script>-->
            </div>
            <?php if ($this->arrContentLastedList): ?>
                <h4 class="name">Suggested for you</h4>
                <div class="videos">
                    <?php foreach ($this->arrContentLastedList as $arr_content):
                        $cont_image = json_decode($arr_content['cont_image'], true);
                        ?>
                        <div class="post">
                            <div class="poster"
                                 style="background: url(<?php echo UPLOAD_URL . $cont_image['120x90']; ?>) no-repeat center;">
                                <div class="bg-gradient"></div>
                                <a href="<?php echo $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
                                   title="<?php echo $arr_content['cont_title']; ?>"
                                   class="link">
                                </a>
                            </div>
                            <div class="content">
                                <h3 class="title">
                                    <a href="<?php echo $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
                                       title="<?php echo $arr_content['cont_title']; ?>">
                                        <?php echo $arr_content['cont_title']; ?>
                                    </a>
                                </h3>
                                <p class="view">
                                    <span class="number">
                                        <?php echo number_format($arr_content['cont_views']); ?>
                                    </span>
                                    view
                                </p>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "NewsArticle",
        "mainEntityOfPage": {
            "@type": "WebPage",
            "@id": "<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content_detail['cont_slug'], 'contentId' => $arr_content_detail['cont_id']]) ?>"
        },
        "headline": "<?php echo $arr_content_detail['cont_title']; ?>",
        "image": {
            "@type": "ImageObject",
            "url": "<?php echo $cont_detail_image['640x480'] ?>",
            "height": 480,
            "width": 640
        },
        "datePublished": "<?php echo date('Y/m/d', $arr_content_detail['created_date']); ?>",
        "dateModified": "<?php echo date('Y/m/d', $arr_content_detail['created_date']); ?>",
        "author": {
            "@type": "Person",
            "name": "Youtube (General)"
        },
        "publisher": {
            "@type": "Organization",
            "name": " <?php echo $arr_content_detail['cont_title']; ?> ",
            "logo": {
                "@type": "ImageObject",
                "url": "<?php echo $cont_detail_image['480x360'] ?>",
                "width": 480,
                "height": 360
            }
        },
        "description": "<?php echo $arr_content_detail['cont_description']; ?>"
    }


</script>
