<div id="tag-page" xmlns="http://www.w3.org/1999/html">
    <div class="search-value">
        <h1>
            Keyword
        </h1>
    </div>
    <div class="container page-width">
        <div class="main-content">
            <div class="inside-container">
                <div class="inside">
                    <h4 class="name">
                        <a>List Keyword</a>
                        <span></span>
                    </h4>
                    <div class="videos">
                        <div class="tags">
                            <ul>
                                <?php if (!empty($this->arrKeywordList)):
                                    foreach ($this->arrKeywordList as $key => $arr_key):
                                        ?>
                                        <li style="padding-top: 3px;">
                                            <a href="<?php echo $this->serverUrl() . $this->Url('keyword', array('keySlug' => $arr_key['key_slug'], 'keyId' => $arr_key['key_id'])) ?>"
                                               title="<?php echo $arr_key['key_name']; ?>">
                                                <?php echo $arr_key['key_name']; ?>
                                            </a>
                                            <br/>
                                        </li>
                                        <?php
                                    endforeach;
                                endif;
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    echo $this->paging
    ?>
</div>