<?php foreach ($this->arrContentList as $key => $arr_content):
    $arr_img = json_decode($arr_content['cont_image'], true);
    ?>
    <div class="post">
        <div class="poster"
             style="background-image: url(<?php echo $arr_img['320x180'] ?>);">
            <div class="bg-gradient"></div>
            <p class="duration">00:36</p>
            <p class="view">
                <span class="number">
                    <?php echo $arr_content['cont_views']; ?>
                </span>
                view
            </p>
            <a href="<?php echo $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
               title="<?php echo $arr_content['cont_title'] ?>"
               class="link">
            </a>
        </div>
        <div class="content">
            <h3 class="title">
                <a href="<?php echo $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
                   title="<?php echo $arr_content['cont_title'] ?>">
                    <?php echo $arr_content['cont_title']; ?>
                </a>
            </h3>
            <p class="description"><?php echo $arr_content['cont_description']; ?></p>
        </div>
    </div>
<?php endforeach; ?>