<footer id="footer">
    <div class="about">
        <div class="page-width">
            <div class="description">
                <img src="<?php echo STATIC_URL;?>/images/general/logo-white-380x120.png"
                     alt="Logo Thatvidieu">
                <p>Kênh chia sẽ video giải trí hàng đầu Việt Nam. Thật vi diệu được thực hiện và ủng hộ bởi đông đảo
                    cộng đồng cùng chia sẻ những khoảnh khắc hài hước, ý nghĩa của mình và bạn bè.</p>
                <div class="social">
                    <div class="follow-us">
                        <p>Theo dõi thêm</p>
                        <ul>
                            <li class="facebook"><a href="https://www.facebook.com/Thật-Vi-Diệu-1116825608374835"
                                                    target="_blank"></a></li>
                            <li class="google"><a href="#"
                                                  onclick="Main.notification('Chức năng đang cập nhật :)'); return false;"></a>
                            </li>
                            <li class="twitter"><a href="#"
                                                   onclick="Main.notification('Chức năng đang cập nhật :)'); return false;"></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="menu">
                <p class="title-menu">Về chúng tôi</p>
                <p class="description-menu">Thông tin về thatvidieu.com</p>
                <ul>
                    <li><a href="about/index.html#info">Giới thiệu</a></li>
                    <li><a href="about/index.html#terms">Điều khoản</a></li>
                    <li><a href="about/index.html#contact">Liên hệ</a></li>
                </ul>
            </div>
            <div class="menu mobile-apps">
                <p class="title-menu">Ứng dụng Mobile</p>
                <p class="description-menu">Cho bạn trải nghiệm tốt hơn</p>
                <ul>
                    <li><a href="#"><span class="icon ios"></span> iOS</a></li>
                    <li><a href="https://play.google.com/store/apps/details?id=net.youthdev.app.thatvidieu"
                           target="_blank"><span class="icon android"></span> Android</a></li>
                    <li><a href="#"><span class="icon wp"></span> Windows Phone</a></li>
                </ul>
            </div>
            <div class="tags">
                <p class="title-tags">Tags</p>
                <p class="description-tags">Danh sách tag nổi bật</p>
                <ul>
                    <li>
                        <a href="tag/hai-huoc.html" title="Hài hước">
                            Hài hước </a>
                    </li>
                    <li>
                        <a href="tag/tinh-cam.html" title="Tình cảm">
                            Tình cảm </a>
                    </li>
                    <li>
                        <a href="tag/dong-vat.html" title="Động vật">
                            Động vật </a>
                    </li>
                    <li>
                        <a href="tag/cong-dong.html" title="Cộng đồng">
                            Cộng đồng </a>
                    </li>
                    <li>
                        <a href="tag/cam-dong.html" title="Cảm động">
                            Cảm động </a>
                    </li>
                    <li>
                        <a href="tag/y-nghia.html" title="Ý nghĩa">
                            Ý nghĩa </a>
                    </li>
                    <li>
                        <a href="tag/buc-xuc.html" title="Bức xúc">
                            Bức xúc </a>
                    </li>
                    <li>
                        <a href="tag/troll.html" title="Troll">
                            Troll </a>
                    </li>
                    <li>
                        <a href="tag/tre-em.html" title="Trẻ em">
                            Trẻ em </a>
                    </li>
                    <li>
                        <a href="tag/shock.html" title="Shock">
                            Shock </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="copyright">
        <div class="page-width">
            <p>Giấy phép MXH số 521/GP-BTTTT cấp ngày 24/11/2016</p>
            <p>Cơ quan cấp phép: Bộ Thông tin và Truyền thông</p>
            <p>Chịu trách nhiệm nội dung: Mai Phạm Thanh Lâm</p>
            <p>Bản quyền thuộc về thatvidieu.com © 2016</p>
        </div>
    </div>
</footer>