<div id="footer" class="clearfix">
    <div class="info">
        <a href="contact.html" rel="nofollow">Liên hệ với chúng tôi</a> -
        <a href="<?php echo \My\General::SOCIAL_FACEBOOK_URL; ?>" target="_blank" rel="nofollow">Khoa học trên
            Facebook</a> -
        <a href="<?php echo $this->serverUrl() . $this->Url('sitemap') ?>" target="_blank" rel="nofollow">Rss</a>
    </div>
    <div class="copyright">
        Copyright © 2016 <?php echo \My\General::SITE_AUTH; ?>
    </div>
</div>