<?php $arrTag = unserialize(ARR_TAG); ?>
<footer id="footer">
    <div class="about">
        <div class="page-width">
            <div class="description">
                <img src="<?php echo STATIC_URL; ?>/images/general/logo-white-380x120.png"
                     alt="Logo Thatvidieu">
                <p>
                    <?php echo \My\General::SITE_DOMAIN; ?> is website general hot video, funny videos, music videos,
                    video beauty ... Brought to you comfortable moments after hours of hard work.
                </p>
                <div class="social">
                    <div class="follow-us">
                        <p>Follow US</p>
                        <ul>
                            <li class="facebook">
                                <a href="<?php echo \My\General::SOCIAL_FACEBOOK_URL; ?>" target="_blank"></a>
                            </li>
                            <li class="google">
                                <a href="<?php echo \My\General::SOCIAL_GOOGLE_PLUS_URL; ?>" target="_blank">
                                </a>
                            </li>
                            <li class="twitter">
                                <a href="<?php echo \My\General::SOCIAL_TWITTER_URL; ?>" target="_blank"></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="menu">
                <p class="title-menu">About US</p>
                <p class="description-menu">Info <?php echo \My\General::SITE_DOMAIN; ?></p>
                <ul>
                    <li><a href="about/index.html#info">Introduce</a></li>
                    <li><a href="about/index.html#terms">Rules</a></li>
                    <li><a href="about/index.html#contact">Contact</a></li>
                </ul>
            </div>
<!--            <div class="menu mobile-apps">-->
<!--                <p class="title-menu">Ứng dụng Mobile</p>-->
<!--                <p class="description-menu">Cho bạn trải nghiệm tốt hơn</p>-->
<!--                <ul>-->
<!--                    <li><a href="#"><span class="icon ios"></span> iOS</a></li>-->
<!--                    <li><a href="https://play.google.com/store/apps/details?id=net.youthdev.app.thatvidieu"-->
<!--                           target="_blank"><span class="icon android"></span> Android</a></li>-->
<!--                    <li><a href="#"><span class="icon wp"></span> Windows Phone</a></li>-->
<!--                </ul>-->
<!--            </div>-->
            <div class="tags">
                <p class="title-tags">Tags</p>
                <p class="description-tags">List Tag Highlights</p>
                <ul>
                    <?php foreach ($arrTag as $tag): ?>
                        <li>
                            <a href="<?php echo $this->Url('tag', array('tagSlug' => $tag['tag_slug'], 'tagId' => $tag['tag_id'])) ?>" title="<?php echo $tag['tag_name'] ?>">
                                <?php echo $tag['tag_name'] ?> </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</footer>