<?php $arr_category = unserialize(ARR_CATEGORY); ?>
<!-- Cover Page -->
<div id="cover-page"></div>
<header id="header">
    <div class="menu">
        <a href="#" class="btn-menu"></a>
        <div class="page-width" style="position: relative;">
            <div class="logo-container">
                <a href="/" class="logo">
                    <img src="<?php echo STATIC_URL; ?>/fe/images/logo_for_tet.png" alt="Logo ShareVideoClip">
                </a>
            </div>
            <ul class="categories">
                <?php foreach ($arr_category as $category): ?>
                    <li>
                        <a href="<?php echo $this->Url('category', ['cateSlug' => $category['cate_slug'], 'cateId' => $category['cate_id']]) ?>"><?php echo $category['cate_name'] ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
            <a href="#" class="btn-search"></a>
        </div>
    </div>
</header>
<div id="search">
    <div class="over">
        <a href="#" class="btn-close"></a>
        <div class="container">
            <form class="search-form" action="<?php echo $this->Url('search', []) ?>">
                <input class="question" name="keyword" type="text" placeholder="Keyword..."
                       value="<?php echo empty(KEYWORD_SEARCH) ? '' : KEYWORD_SEARCH; ?>">
                <button class="btn-submit" type="submit"></button>
            </form>
        </div>
    </div>
</div>