<div class="sidebar">
    <div class="type hot">
        <h4 class="name">
            <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                 alt="icon"/>
            <a href="hot-today/index.html">HOT NOW</a>
            <span></span>
        </h4>
        <div class="container">
            <div class="bg-type">
                <img src="<?php echo STATIC_URL; ?>/images/homepage/bg-hot-700x226.jpg"
                     alt="Default Background"/>
            </div>
            <div class="videos">
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/b932969dada305b7c9ec8798fb5e11a4.jpg);">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/b932969dada305b7c9ec8798fb5e11a4.jpg"
                            title="20 MV US-UK có lượt xem khủng nhất trên Youtube"
                            alt="20 MV US-UK có lượt xem khủng nhất trên Youtube"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top1">01</p>
                        <a href="post/18211-20-mv-us-uk-co-luot-xem-khung-nhat-tren-youtube.html"
                           title="20 MV US-UK có lượt xem khủng nhất trên Youtube"
                           class="link">
                        </a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18211-20-mv-us-uk-co-luot-xem-khung-nhat-tren-youtube.html"
                               title="20 MV US-UK có lượt xem khủng nhất trên Youtube">
                                20 MV US-UK có lượt xem khủng nhất trên Youtube </a>
                        </h3>
                        <p class="hot">ĐỘ HOT <span class="score">148</span></p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/5cacb83ff6c61fd55d263900ca89ee7f.jpg);">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/5cacb83ff6c61fd55d263900ca89ee7f.jpg"
                            title="Tui cá cái mà bạn chú ý không phải là hình xăm của cô gái ấy..."
                            alt="Tui cá cái mà bạn chú ý không phải là hình xăm của cô gái ấy..."
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top2">02</p>
                        <a href="post/18212-tui-ca-cai-ma-ban-chu-y-khong-phai-la-hinh-xam-cua-co-gai-ay.html"
                           title="Tui cá cái mà bạn chú ý không phải là hình xăm của cô gái ấy..."
                           class="link">
                        </a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18212-tui-ca-cai-ma-ban-chu-y-khong-phai-la-hinh-xam-cua-co-gai-ay.html"
                               title="Tui cá cái mà bạn chú ý không phải là hình xăm của cô gái ấy...">
                                Tui cá cái mà bạn chú ý không phải là hình xăm của cô gái ấy... </a>
                        </h3>
                        <p class="hot">ĐỘ HOT <span class="score">96</span></p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/edbe977edf697cf61b28f0a84c2205e9.jpg);">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/edbe977edf697cf61b28f0a84c2205e9.jpg"
                            title="&quot;What are words&quot; - bài hát làm cả thế giới khóc..."
                            alt="&quot;What are words&quot; - bài hát làm cả thế giới khóc..."
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top3">03</p>
                        <a href="post/18195-what-are-words-bai-hat-lam-ca-the-gioi-khoc.html"
                           title="&quot;What are words&quot; - bài hát làm cả thế giới khóc..."
                           class="link">
                        </a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18195-what-are-words-bai-hat-lam-ca-the-gioi-khoc.html"
                               title="&quot;What are words&quot; - bài hát làm cả thế giới khóc...">
                                &quot;What are words&quot; - bài hát làm cả thế giới khóc... </a>
                        </h3>
                        <p class="hot">ĐỘ HOT <span class="score">63</span></p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/40d4ad77346c3865966ea1eceed97846.jpg);">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/40d4ad77346c3865966ea1eceed97846.jpg"
                            title="Cô gái xinh đẹp cover &quot;The Show&quot; của Lenka cực dễ thương :*"
                            alt="Cô gái xinh đẹp cover &quot;The Show&quot; của Lenka cực dễ thương :*"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">04</p>
                        <a href="post/18220-co-gai-xinh-dep-cover-the-show-cua-lenka-cuc-de-thuong.html"
                           title="Cô gái xinh đẹp cover &quot;The Show&quot; của Lenka cực dễ thương :*"
                           class="link">
                        </a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18220-co-gai-xinh-dep-cover-the-show-cua-lenka-cuc-de-thuong.html"
                               title="Cô gái xinh đẹp cover &quot;The Show&quot; của Lenka cực dễ thương :*">
                                Cô gái xinh đẹp cover &quot;The Show&quot; của Lenka cực dễ thương
                                :* </a>
                        </h3>
                        <p class="hot">ĐỘ HOT <span class="score">63</span></p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/fd547c4268be075a5b889de53370bd39.jpg);">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/fd547c4268be075a5b889de53370bd39.jpg"
                            title="Tự thiết kế đầm cho búp bê cưng nè các cô gái :*"
                            alt="Tự thiết kế đầm cho búp bê cưng nè các cô gái :*"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">05</p>
                        <a href="post/18216-tu-thiet-ke-dam-cho-bup-be-cung-ne-cac-co-gai.html"
                           title="Tự thiết kế đầm cho búp bê cưng nè các cô gái :*"
                           class="link">
                        </a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18216-tu-thiet-ke-dam-cho-bup-be-cung-ne-cac-co-gai.html"
                               title="Tự thiết kế đầm cho búp bê cưng nè các cô gái :*">
                                Tự thiết kế đầm cho búp bê cưng nè các cô gái :* </a>
                        </h3>
                        <p class="hot">ĐỘ HOT <span class="score">49</span></p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/ee24d1a8137dcae8e5665e29141dcacb.jpg);">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/ee24d1a8137dcae8e5665e29141dcacb.jpg"
                            title="Muốn bớt đau khổ, hãy tự làm ra tiền..."
                            alt="Muốn bớt đau khổ, hãy tự làm ra tiền..."
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">06</p>
                        <a href="post/18205-muon-bot-dau-kho-hay-tu-lam-ra-tien.html"
                           title="Muốn bớt đau khổ, hãy tự làm ra tiền..."
                           class="link">
                        </a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18205-muon-bot-dau-kho-hay-tu-lam-ra-tien.html"
                               title="Muốn bớt đau khổ, hãy tự làm ra tiền...">
                                Muốn bớt đau khổ, hãy tự làm ra tiền... </a>
                        </h3>
                        <p class="hot">ĐỘ HOT <span class="score">46</span></p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/5680c290ac894720e9888a0d49bf0c79.jpg);">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/5680c290ac894720e9888a0d49bf0c79.jpg"
                            title="Phim &quot;Sword Master&quot; - Thần kiếm| Những pha đấu kiếm đã mắt (y) "
                            alt="Phim &quot;Sword Master&quot; - Thần kiếm| Những pha đấu kiếm đã mắt (y) "
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">07</p>
                        <a href="post/18196-phim-sword-master-than-kiem-nhung-pha-dau-kiem-da-mat-y.html"
                           title="Phim &quot;Sword Master&quot; - Thần kiếm| Những pha đấu kiếm đã mắt (y) "
                           class="link">
                        </a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18196-phim-sword-master-than-kiem-nhung-pha-dau-kiem-da-mat-y.html"
                               title="Phim &quot;Sword Master&quot; - Thần kiếm| Những pha đấu kiếm đã mắt (y) ">
                                Phim &quot;Sword Master&quot; - Thần kiếm| Những pha đấu kiếm đã mắt
                                (y) </a>
                        </h3>
                        <p class="hot">ĐỘ HOT <span class="score">40</span></p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/4b93c2c616eab67341893a673455c7d9.jpg);">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/4b93c2c616eab67341893a673455c7d9.jpg"
                            title="Gala hài xuân 2017: Trường Giang còn phải ngả mũ trước độ lầy của Thiên Vương ;)"
                            alt="Gala hài xuân 2017: Trường Giang còn phải ngả mũ trước độ lầy của Thiên Vương ;)"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">08</p>
                        <a href="post/18213-gala-hai-xuan-2017-truong-giang-con-phai-nga-mu-truoc-do-lay-cua-thien-vuong.html"
                           title="Gala hài xuân 2017: Trường Giang còn phải ngả mũ trước độ lầy của Thiên Vương ;)"
                           class="link">
                        </a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18213-gala-hai-xuan-2017-truong-giang-con-phai-nga-mu-truoc-do-lay-cua-thien-vuong.html"
                               title="Gala hài xuân 2017: Trường Giang còn phải ngả mũ trước độ lầy của Thiên Vương ;)">
                                Gala hài xuân 2017: Trường Giang còn phải ngả mũ trước độ lầy của
                                Thiên Vương ;) </a>
                        </h3>
                        <p class="hot">ĐỘ HOT <span class="score">36</span></p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/718ddf12c6a210f67157e8c9c012b432.jpg);">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/718ddf12c6a210f67157e8c9c012b432.jpg"
                            title="Hít bóng cười... lần đầu làm chuyện ấy :v"
                            alt="Hít bóng cười... lần đầu làm chuyện ấy :v"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">09</p>
                        <a href="post/18214-hit-bong-cuoi-lan-dau-lam-chuyen-ay-v.html"
                           title="Hít bóng cười... lần đầu làm chuyện ấy :v"
                           class="link">
                        </a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18214-hit-bong-cuoi-lan-dau-lam-chuyen-ay-v.html"
                               title="Hít bóng cười... lần đầu làm chuyện ấy :v">
                                Hít bóng cười... lần đầu làm chuyện ấy :v </a>
                        </h3>
                        <p class="hot">ĐỘ HOT <span class="score">36</span></p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/d9d236272a4c3d19b8aa600a4476d897.jpg);">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/d9d236272a4c3d19b8aa600a4476d897.jpg"
                            title="Sau PPAP, đây chính là bài hát đang gây bão cộng đồng mạng =))"
                            alt="Sau PPAP, đây chính là bài hát đang gây bão cộng đồng mạng =))"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">10</p>
                        <a href="post/18167-sau-ppap-day-chinh-la-bai-hat-dang-gay-bao-cong-dong-mang.html"
                           title="Sau PPAP, đây chính là bài hát đang gây bão cộng đồng mạng =))"
                           class="link">
                        </a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18167-sau-ppap-day-chinh-la-bai-hat-dang-gay-bao-cong-dong-mang.html"
                               title="Sau PPAP, đây chính là bài hát đang gây bão cộng đồng mạng =))">
                                Sau PPAP, đây chính là bài hát đang gây bão cộng đồng mạng =)) </a>
                        </h3>
                        <p class="hot">ĐỘ HOT <span class="score">30</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="type feature">
        <h4 class="name">
            <img src="<?php echo STATIC_URL; ?>/images/homepage/icon-feature-42x57.png"
                 alt="icon"/>
            <a href="ranking.html">BXH TUẦN</a>
            <span></span>
        </h4>
        <div class="container">
            <div class="bg-type">
                <img src="<?php echo STATIC_URL; ?>/images/homepage/bg-feature-700x226.jpg"
                     alt="Default Background"/>
            </div>
            <div class="videos">
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/ee000553ff3a10bd6c83022548b74d01.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/ee000553ff3a10bd6c83022548b74d01.jpg"
                            title="Đâu là thời điểm tốt nhất để buông bỏ ?"
                            alt="Đâu là thời điểm tốt nhất để buông bỏ ?"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top1">01</p>
                        <a href="post/18082-dau-la-thoi-diem-tot-nhat-de-buong-bo.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18082-dau-la-thoi-diem-tot-nhat-de-buong-bo.html"
                               title="Đâu là thời điểm tốt nhất để buông bỏ ?">
                                Đâu là thời điểm tốt nhất để buông bỏ ? </a>
                        </h3>
                        <p class="hot"><span class="score">18</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/1272fe802c494d2e5c26af48afee3ebd.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/1272fe802c494d2e5c26af48afee3ebd.jpg"
                            title="Cách mở khóa Iphone ai cũng có thể làm được ;)"
                            alt="Cách mở khóa Iphone ai cũng có thể làm được ;)"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top2">02</p>
                        <a href="post/18084-cach-mo-khoa-iphone-ai-cung-co-the-lam-duoc.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18084-cach-mo-khoa-iphone-ai-cung-co-the-lam-duoc.html"
                               title="Cách mở khóa Iphone ai cũng có thể làm được ;)">
                                Cách mở khóa Iphone ai cũng có thể làm được ;) </a>
                        </h3>
                        <p class="hot"><span class="score">17</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/1e3f857c0aa58f8f7b63ba7f67e87be0.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/1e3f857c0aa58f8f7b63ba7f67e87be0.jpg"
                            title="Lại một vụ bạo hành trẻ em gây bức xúc cộng đồng mạng &gt;.&lt;"
                            alt="Lại một vụ bạo hành trẻ em gây bức xúc cộng đồng mạng &gt;.&lt;"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top3">03</p>
                        <a href="post/18149-lai-mot-vu-bao-hanh-tre-em-gay-buc-xuc-cong-dong-mang.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18149-lai-mot-vu-bao-hanh-tre-em-gay-buc-xuc-cong-dong-mang.html"
                               title="Lại một vụ bạo hành trẻ em gây bức xúc cộng đồng mạng &gt;.&lt;">
                                Lại một vụ bạo hành trẻ em gây bức xúc cộng đồng mạng
                                &gt;.&lt;                                            </a>
                        </h3>
                        <p class="hot"><span class="score">17</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/17ffc7c3c2f505cbdd43e2f9f21e9d69.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/17ffc7c3c2f505cbdd43e2f9f21e9d69.jpg"
                            title="Điều kì diệu gì đã xảy ra sau một tai nạn ở Hàn Quốc?"
                            alt="Điều kì diệu gì đã xảy ra sau một tai nạn ở Hàn Quốc?"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">04</p>
                        <a href="post/18109-dieu-ki-dieu-gi-da-xay-ra-sau-mot-tai-nan-o-han-quoc.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18109-dieu-ki-dieu-gi-da-xay-ra-sau-mot-tai-nan-o-han-quoc.html"
                               title="Điều kì diệu gì đã xảy ra sau một tai nạn ở Hàn Quốc?">
                                Điều kì diệu gì đã xảy ra sau một tai nạn ở Hàn Quốc? </a>
                        </h3>
                        <p class="hot"><span class="score">16</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/9ead3158a793525feb249ee30375bb1e.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/9ead3158a793525feb249ee30375bb1e.jpg"
                            title="Tội nghiệp em chó quá :'("
                            alt="Tội nghiệp em chó quá :'("
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">05</p>
                        <a href="post/18104-toi-nghiep-em-cho-qua.html" class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18104-toi-nghiep-em-cho-qua.html"
                               title="Tội nghiệp em chó quá :'(">
                                Tội nghiệp em chó quá :'( </a>
                        </h3>
                        <p class="hot"><span class="score">13</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/b245225a1415d8e656c34f7033a42f28.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/b245225a1415d8e656c34f7033a42f28.jpg"
                            title="Con dù lớn vẫn là con của Mẹ.... Cả đời con nợ Mẹ công sinh thành!"
                            alt="Con dù lớn vẫn là con của Mẹ.... Cả đời con nợ Mẹ công sinh thành!"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">06</p>
                        <a href="post/14888-con-du-lon-van-la-con-cua-me-ca-doi-con-no-me-cong-sinh-thanh.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/14888-con-du-lon-van-la-con-cua-me-ca-doi-con-no-me-cong-sinh-thanh.html"
                               title="Con dù lớn vẫn là con của Mẹ.... Cả đời con nợ Mẹ công sinh thành!">
                                Con dù lớn vẫn là con của Mẹ.... Cả đời con nợ Mẹ công sinh
                                thành! </a>
                        </h3>
                        <p class="hot"><span class="score">13</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/08c66da60f4de2d58718c97eec8a4262.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/08c66da60f4de2d58718c97eec8a4262.jpg"
                            title="4 mẹo hay bạn nhất định phải biết !"
                            alt="4 mẹo hay bạn nhất định phải biết !"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">07</p>
                        <a href="post/18086-4-meo-hay-ban-nhat-dinh-phai-biet.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18086-4-meo-hay-ban-nhat-dinh-phai-biet.html"
                               title="4 mẹo hay bạn nhất định phải biết !">
                                4 mẹo hay bạn nhất định phải biết ! </a>
                        </h3>
                        <p class="hot"><span class="score">11</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/90263e54bde37283e276343a569d3649.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/90263e54bde37283e276343a569d3649.jpg"
                            title="Cảnh báo: hiểm họa cháy nổ từ... cáp treo !"
                            alt="Cảnh báo: hiểm họa cháy nổ từ... cáp treo !"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">08</p>
                        <a href="post/18089-canh-bao-hiem-hoa-chay-no-tu-cap-treo.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18089-canh-bao-hiem-hoa-chay-no-tu-cap-treo.html"
                               title="Cảnh báo: hiểm họa cháy nổ từ... cáp treo !">
                                Cảnh báo: hiểm họa cháy nổ từ... cáp treo ! </a>
                        </h3>
                        <p class="hot"><span class="score">11</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/10be9fa241e99f3723745878302973b7.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/10be9fa241e99f3723745878302973b7.jpg"
                            title="Ad đã khóc thương cho chú chó này, cho đến khi..."
                            alt="Ad đã khóc thương cho chú chó này, cho đến khi..."
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">09</p>
                        <a href="post/18114-ad-da-khoc-thuong-cho-chu-cho-nay-cho-den-khi.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18114-ad-da-khoc-thuong-cho-chu-cho-nay-cho-den-khi.html"
                               title="Ad đã khóc thương cho chú chó này, cho đến khi...">
                                Ad đã khóc thương cho chú chó này, cho đến khi... </a>
                        </h3>
                        <p class="hot"><span class="score">10</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/d9d236272a4c3d19b8aa600a4476d897.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/d9d236272a4c3d19b8aa600a4476d897.jpg"
                            title="Sau PPAP, đây chính là bài hát đang gây bão cộng đồng mạng =))"
                            alt="Sau PPAP, đây chính là bài hát đang gây bão cộng đồng mạng =))"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">10</p>
                        <a href="post/18167-sau-ppap-day-chinh-la-bai-hat-dang-gay-bao-cong-dong-mang.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18167-sau-ppap-day-chinh-la-bai-hat-dang-gay-bao-cong-dong-mang.html"
                               title="Sau PPAP, đây chính là bài hát đang gây bão cộng đồng mạng =))">
                                Sau PPAP, đây chính là bài hát đang gây bão cộng đồng mạng =)) </a>
                        </h3>
                        <p class="hot"><span class="score">10</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/c56c3308eb0570883f14b04a65c9d324.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/c56c3308eb0570883f14b04a65c9d324.jpg"
                            title="&quot;Không ngăn được lý trí&quot; - Hiền Thục: 1 bài hát mất 3 năm để học..."
                            alt="&quot;Không ngăn được lý trí&quot; - Hiền Thục: 1 bài hát mất 3 năm để học..."
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">11</p>
                        <a href="post/18105-khong-ngan-duoc-ly-tri-hien-thuc-1-bai-hat-mat-3-nam-de-hoc.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18105-khong-ngan-duoc-ly-tri-hien-thuc-1-bai-hat-mat-3-nam-de-hoc.html"
                               title="&quot;Không ngăn được lý trí&quot; - Hiền Thục: 1 bài hát mất 3 năm để học...">
                                &quot;Không ngăn được lý trí&quot; - Hiền Thục: 1 bài hát mất 3 năm
                                để học... </a>
                        </h3>
                        <p class="hot"><span class="score">10</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/954489db062995320f34fb29bd852d02.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/954489db062995320f34fb29bd852d02.jpg"
                            title="Là con trai, phải bảo vệ và che chở cho người mình yêu, chứ đừng làm cô ấy phải khóc vì mình!"
                            alt="Là con trai, phải bảo vệ và che chở cho người mình yêu, chứ đừng làm cô ấy phải khóc vì mình!"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">12</p>
                        <a href="post/12326-la-con-trai-phai-bao-ve-va-che-cho-cho-nguoi-minh-yeu-chu-dung-lam-co-ay-phai-khoc-vi-minh.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/12326-la-con-trai-phai-bao-ve-va-che-cho-cho-nguoi-minh-yeu-chu-dung-lam-co-ay-phai-khoc-vi-minh.html"
                               title="Là con trai, phải bảo vệ và che chở cho người mình yêu, chứ đừng làm cô ấy phải khóc vì mình!">
                                Là con trai, phải bảo vệ và che chở cho người mình yêu, chứ đừng làm
                                cô ấy phải khóc vì mình! </a>
                        </h3>
                        <p class="hot"><span class="score">10</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/d11453cb8bfc38244e21353db3e37d63.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/d11453cb8bfc38244e21353db3e37d63.jpg"
                            title="Ai đang vấp ngã hãy nghe lời Bồ Tát &quot;khuyên con&quot; &lt;3"
                            alt="Ai đang vấp ngã hãy nghe lời Bồ Tát &quot;khuyên con&quot; &lt;3"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">13</p>
                        <a href="post/18085-ai-dang-vap-nga-hay-nghe-loi-bo-tat-khuyen-con-3.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18085-ai-dang-vap-nga-hay-nghe-loi-bo-tat-khuyen-con-3.html"
                               title="Ai đang vấp ngã hãy nghe lời Bồ Tát &quot;khuyên con&quot; &lt;3">
                                Ai đang vấp ngã hãy nghe lời Bồ Tát &quot;khuyên con&quot;
                                &lt;3 </a>
                        </h3>
                        <p class="hot"><span class="score">10</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/39a729df1fe7915663406ff49c168066.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/39a729df1fe7915663406ff49c168066.jpg"
                            title="Chuyện lạ có thật: bầu trời phát ánh hào quang..."
                            alt="Chuyện lạ có thật: bầu trời phát ánh hào quang..."
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">14</p>
                        <a href="post/18123-chuyen-la-co-that-bau-troi-phat-anh-hao-quang.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18123-chuyen-la-co-that-bau-troi-phat-anh-hao-quang.html"
                               title="Chuyện lạ có thật: bầu trời phát ánh hào quang...">
                                Chuyện lạ có thật: bầu trời phát ánh hào quang... </a>
                        </h3>
                        <p class="hot"><span class="score">9</span> Điểm</p>
                    </div>
                </div>
                <div class="post">
                    <div class="poster"
                         style="background-image: url(<?php echo STATIC_URL ?>/picture/small/4c3c9df4dbaeff384431bbc1e3437868.jpg)">
                        <img
                            src="<?php echo STATIC_URL ?>/picture/small/4c3c9df4dbaeff384431bbc1e3437868.jpg"
                            title="Hot: 20 MV Vpop có lượt xem khủng nhất trên Youtube 2016"
                            alt="Hot: 20 MV Vpop có lượt xem khủng nhất trên Youtube 2016"
                            class="thumbnail"
                        />
                        <div class="bg-gradient"></div>
                        <p class="number top">15</p>
                        <a href="post/18083-hot-20-mv-vpop-co-luot-xem-khung-nhat-tren-youtube-2016.html"
                           class="link"></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a href="post/18083-hot-20-mv-vpop-co-luot-xem-khung-nhat-tren-youtube-2016.html"
                               title="Hot: 20 MV Vpop có lượt xem khủng nhất trên Youtube 2016">
                                Hot: 20 MV Vpop có lượt xem khủng nhất trên Youtube 2016 </a>
                        </h3>
                        <p class="hot"><span class="score">8</span> Điểm</p>
                    </div>
                </div>
            </div>
            <div class="bg-type">
                <img
                    src="<?php echo STATIC_URL; ?>/images/homepage/bg-feature-2-700x236.jpg"
                    alt="Default Background"/>
            </div>
        </div>
    </div>
</div>