<section id="searchBar">
    <div class="container">
        <div class="row pull-right">
            <div class="col-md-12 pull-right">
                <form method="post">
                    <input class="keyword" type="text" name="keyword" placeholder="Enter Keyword Here...">
                    <div class="label">
                        <select class="select">
                            <option>Fashion</option>
                            <option>House</option>
                            <option>Electronics</option>
                        </select>
                    </div>
                    <div class="label">
                        <select class="select">
                            <option>Location</option>
                            <option>USA</option>
                            <option>UK</option>
                        </select>
                    </div>
                    <a href="#" class="location">
                        <i class="fa fa fa-location-arrow "></i>
                    </a>
                    <div class="location-tip">
                        <span class="location-range">499 km</span>
                    </div>
                    <button type="submit" name="submit" class="search-btn">Go Search</button>
                </form>
            </div>
        </div>
    </div>
</section>