<div class="sidebar">
    <h4 class="name">Xem nhiều nhất</h4>
    <div class="videos">
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/8eb50afe89f34b6e73ca983be1475424.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/8eb50afe89f34b6e73ca983be1475424.jpg"
                     title="Xe khách 29 chỗ nhét 93 người - còn chỗ nào để thở không ? :o"
                     alt="Xe khách 29 chỗ nhét 93 người - còn chỗ nào để thở không ? :o"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/17447-xe-khach-29-cho-nhet-93-nguoi-con-cho-nao-de-tho-khong-o.html"
                   title="Xe khách 29 chỗ nhét 93 người - còn chỗ nào để thở không ? :o"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/17447-xe-khach-29-cho-nhet-93-nguoi-con-cho-nao-de-tho-khong-o.html"
                       title="Xe khách 29 chỗ nhét 93 người - còn chỗ nào để thở không ? :o">
                        Xe khách 29 chỗ nhét 93 người - còn chỗ nào để thở không ? :o </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">457,105</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/1700fbe978286612dfde464993eb2361.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/1700fbe978286612dfde464993eb2361.jpg"
                     title="Bất ngờ với hành động của thanh niên khi gặp cậu bé ngủ ngoài đường!"
                     alt="Bất ngờ với hành động của thanh niên khi gặp cậu bé ngủ ngoài đường!"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/18051-bat-ngo-voi-hanh-dong-cua-thanh-nien-khi-gap-cau-be-ngu-ngoai-duong.html"
                   title="Bất ngờ với hành động của thanh niên khi gặp cậu bé ngủ ngoài đường!"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/18051-bat-ngo-voi-hanh-dong-cua-thanh-nien-khi-gap-cau-be-ngu-ngoai-duong.html"
                       title="Bất ngờ với hành động của thanh niên khi gặp cậu bé ngủ ngoài đường!">
                        Bất ngờ với hành động của thanh niên khi gặp cậu bé ngủ ngoài đường! </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">11,250,860</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/609366050cef4902e4576a451fe29a3e.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/609366050cef4902e4576a451fe29a3e.jpg"
                     title="Công thức tạc tượng bàn tay siêu bất ngờ !!!"
                     alt="Công thức tạc tượng bàn tay siêu bất ngờ !!!"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/18048-cong-thuc-tac-tuong-ban-tay-sieu-bat-ngo.html"
                   title="Công thức tạc tượng bàn tay siêu bất ngờ !!!"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/18048-cong-thuc-tac-tuong-ban-tay-sieu-bat-ngo.html"
                       title="Công thức tạc tượng bàn tay siêu bất ngờ !!!">
                        Công thức tạc tượng bàn tay siêu bất ngờ !!! </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">52,872,481</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/c2591e1ee860943cf02d325531e07aa8.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/c2591e1ee860943cf02d325531e07aa8.jpg"
                     title="Thấy &quot;chuối&quot; là mê à và cái kết cho cô gái =))"
                     alt="Thấy &quot;chuối&quot; là mê à và cái kết cho cô gái =))"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/15707-thay-chuoi-la-me-a-va-cai-ket-cho-co-gai.html"
                   title="Thấy &quot;chuối&quot; là mê à và cái kết cho cô gái =))"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/15707-thay-chuoi-la-me-a-va-cai-ket-cho-co-gai.html"
                       title="Thấy &quot;chuối&quot; là mê à và cái kết cho cô gái =))">
                        Thấy &quot;chuối&quot; là mê à và cái kết cho cô gái =)) </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">11,276,314</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/32374562508bb2509906c8fc1e947ce1.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/32374562508bb2509906c8fc1e947ce1.jpg"
                     title="Bản Remix &quot;Lạc Trôi &quot; này đã khiến các Sky phải điên đảo :o"
                     alt="Bản Remix &quot;Lạc Trôi &quot; này đã khiến các Sky phải điên đảo :o"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/16032-ban-remix-lac-troi-nay-da-khien-cac-sky-phai-dien-dao-o.html"
                   title="Bản Remix &quot;Lạc Trôi &quot; này đã khiến các Sky phải điên đảo :o"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/16032-ban-remix-lac-troi-nay-da-khien-cac-sky-phai-dien-dao-o.html"
                       title="Bản Remix &quot;Lạc Trôi &quot; này đã khiến các Sky phải điên đảo :o">
                        Bản Remix &quot;Lạc Trôi &quot; này đã khiến các Sky phải điên đảo :o </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">693,290</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/5e67c35da3e126dd6ec952d97823e625.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/5e67c35da3e126dd6ec952d97823e625.jpg"
                     title="Thôi, cháu lớn rồi... Mừng tuổi gấp đôi =)))"
                     alt="Thôi, cháu lớn rồi... Mừng tuổi gấp đôi =)))"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/18059-thoi-chau-lon-roi-mung-tuoi-gap-doi.html"
                   title="Thôi, cháu lớn rồi... Mừng tuổi gấp đôi =)))"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/18059-thoi-chau-lon-roi-mung-tuoi-gap-doi.html"
                       title="Thôi, cháu lớn rồi... Mừng tuổi gấp đôi =)))">
                        Thôi, cháu lớn rồi... Mừng tuổi gấp đôi =))) </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">1,224,274</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/7909427d0fb7b251132f78759ccfc6db.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/7909427d0fb7b251132f78759ccfc6db.jpg"
                     title="Màn tập thể hình...bung ngực của cô gái khiến các thanh niên bấn loạn :o "
                     alt="Màn tập thể hình...bung ngực của cô gái khiến các thanh niên bấn loạn :o "
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/17970-man-tap-the-hinhbung-nguc-cua-co-gai-khien-cac-thanh-nien-ban-loan-o.html"
                   title="Màn tập thể hình...bung ngực của cô gái khiến các thanh niên bấn loạn :o "
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/17970-man-tap-the-hinhbung-nguc-cua-co-gai-khien-cac-thanh-nien-ban-loan-o.html"
                       title="Màn tập thể hình...bung ngực của cô gái khiến các thanh niên bấn loạn :o ">
                        Màn tập thể hình...bung ngực của cô gái khiến các thanh niên bấn loạn :o </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">61,766,799</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/01bcdf246a936623359b17ab8f320132.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/01bcdf246a936623359b17ab8f320132.jpg"
                     title="Cô gái hát &quot;Xuân đẹp làm sao&quot; chúc Tết cả nhà - nghe xong nghiện luôn :*"
                     alt="Cô gái hát &quot;Xuân đẹp làm sao&quot; chúc Tết cả nhà - nghe xong nghiện luôn :*"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/18046-co-gai-hat-xuan-dep-lam-sao-chuc-tet-ca-nha-nghe-xong-nghien-luon.html"
                   title="Cô gái hát &quot;Xuân đẹp làm sao&quot; chúc Tết cả nhà - nghe xong nghiện luôn :*"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/18046-co-gai-hat-xuan-dep-lam-sao-chuc-tet-ca-nha-nghe-xong-nghien-luon.html"
                       title="Cô gái hát &quot;Xuân đẹp làm sao&quot; chúc Tết cả nhà - nghe xong nghiện luôn :*">
                        Cô gái hát &quot;Xuân đẹp làm sao&quot; chúc Tết cả nhà - nghe xong nghiện luôn
                        :* </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">868,486</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/aad0fdc809a039af341f870c26ca1430.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/aad0fdc809a039af341f870c26ca1430.jpg"
                     title="Cùng xem các nam các nữ lần đầu phê thuốc Lào....mấy nữ kinh quá =))"
                     alt="Cùng xem các nam các nữ lần đầu phê thuốc Lào....mấy nữ kinh quá =))"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/15712-cung-xem-cac-nam-cac-nu-lan-dau-phe-thuoc-laomay-nu-kinh-qua.html"
                   title="Cùng xem các nam các nữ lần đầu phê thuốc Lào....mấy nữ kinh quá =))"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/15712-cung-xem-cac-nam-cac-nu-lan-dau-phe-thuoc-laomay-nu-kinh-qua.html"
                       title="Cùng xem các nam các nữ lần đầu phê thuốc Lào....mấy nữ kinh quá =))">
                        Cùng xem các nam các nữ lần đầu phê thuốc Lào....mấy nữ kinh quá =)) </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">453,815</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/714e2133ffbdb2db112842f6780737fe.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/714e2133ffbdb2db112842f6780737fe.jpg"
                     title="&quot;Bí kíp tâm lí phụ nữ&quot; :))) mấy chế xem đi nha nha :))"
                     alt="&quot;Bí kíp tâm lí phụ nữ&quot; :))) mấy chế xem đi nha nha :))"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/16080-bi-kip-tam-li-phu-nu-may-che-xem-di-nha-nha.html"
                   title="&quot;Bí kíp tâm lí phụ nữ&quot; :))) mấy chế xem đi nha nha :))"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/16080-bi-kip-tam-li-phu-nu-may-che-xem-di-nha-nha.html"
                       title="&quot;Bí kíp tâm lí phụ nữ&quot; :))) mấy chế xem đi nha nha :))">
                        &quot;Bí kíp tâm lí phụ nữ&quot; :))) mấy chế xem đi nha nha :)) </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">395,575</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/36155e38d63d3c316ef9fc395cb71d08.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/36155e38d63d3c316ef9fc395cb71d08.jpg"
                     title="Phát minh đột phá: miếng băng keo thần kì ! (y)"
                     alt="Phát minh đột phá: miếng băng keo thần kì ! (y)"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/18054-phat-minh-dot-pha-mieng-bang-keo-than-ki-y.html"
                   title="Phát minh đột phá: miếng băng keo thần kì ! (y)"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/18054-phat-minh-dot-pha-mieng-bang-keo-than-ki-y.html"
                       title="Phát minh đột phá: miếng băng keo thần kì ! (y)">
                        Phát minh đột phá: miếng băng keo thần kì ! (y) </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">2,723,043</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/d6967f7d986510624f4a066a04d6cbf6.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/d6967f7d986510624f4a066a04d6cbf6.jpg"
                     title="An Nguy: để đi ngủ sớm thì 1 là cắt mạng, 2 là..."
                     alt="An Nguy: để đi ngủ sớm thì 1 là cắt mạng, 2 là..."
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/17437-an-nguy-de-di-ngu-som-thi-1-la-cat-mang-2-la.html"
                   title="An Nguy: để đi ngủ sớm thì 1 là cắt mạng, 2 là..."
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/17437-an-nguy-de-di-ngu-som-thi-1-la-cat-mang-2-la.html"
                       title="An Nguy: để đi ngủ sớm thì 1 là cắt mạng, 2 là...">
                        An Nguy: để đi ngủ sớm thì 1 là cắt mạng, 2 là... </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">1,400,045</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/dbf10e4cba9c52d43ec67aaf2b8d8e00.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/dbf10e4cba9c52d43ec67aaf2b8d8e00.jpg"
                     title="Một nụ cười thôi hàng triệu nam thanh niên phải gục ngã với nàng Caitlin Minogue"
                     alt="Một nụ cười thôi hàng triệu nam thanh niên phải gục ngã với nàng Caitlin Minogue"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/15220-mot-nu-cuoi-thoi-hang-trieu-nam-thanh-nien-phai-guc-nga-voi-nang-caitlin-minogue.html"
                   title="Một nụ cười thôi hàng triệu nam thanh niên phải gục ngã với nàng Caitlin Minogue"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/15220-mot-nu-cuoi-thoi-hang-trieu-nam-thanh-nien-phai-guc-nga-voi-nang-caitlin-minogue.html"
                       title="Một nụ cười thôi hàng triệu nam thanh niên phải gục ngã với nàng Caitlin Minogue">
                        Một nụ cười thôi hàng triệu nam thanh niên phải gục ngã với nàng Caitlin
                        Minogue </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">298,296</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/6a6cdf8300e4ab940bccc01afdf3b1ac.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/6a6cdf8300e4ab940bccc01afdf3b1ac.jpg"
                     title="Cảnh báo: Nữ sinh bất tỉnh vì bị bạn đập gạch vào đầu..."
                     alt="Cảnh báo: Nữ sinh bất tỉnh vì bị bạn đập gạch vào đầu..."
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/18055-canh-bao-nu-sinh-bat-tinh-vi-bi-ban-dap-gach-vao-dau.html"
                   title="Cảnh báo: Nữ sinh bất tỉnh vì bị bạn đập gạch vào đầu..."
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/18055-canh-bao-nu-sinh-bat-tinh-vi-bi-ban-dap-gach-vao-dau.html"
                       title="Cảnh báo: Nữ sinh bất tỉnh vì bị bạn đập gạch vào đầu...">
                        Cảnh báo: Nữ sinh bất tỉnh vì bị bạn đập gạch vào đầu... </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">689,229</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/fabb0eb3d425967bc9749c68087a94ea.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/fabb0eb3d425967bc9749c68087a94ea.jpg"
                     title="Lý do con gái thích con trai chơi bóng rổ :3"
                     alt="Lý do con gái thích con trai chơi bóng rổ :3"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/16117-ly-do-con-gai-thich-con-trai-choi-bong-ro-3.html"
                   title="Lý do con gái thích con trai chơi bóng rổ :3"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/16117-ly-do-con-gai-thich-con-trai-choi-bong-ro-3.html"
                       title="Lý do con gái thích con trai chơi bóng rổ :3">
                        Lý do con gái thích con trai chơi bóng rổ :3 </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">511,363</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/824793dc76eaab8e53317323d4ac4592.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/824793dc76eaab8e53317323d4ac4592.jpg"
                     title="Bọn bắt cóc trẻ em ngày càng ranh mãnh, hãy cảnh giác !"
                     alt="Bọn bắt cóc trẻ em ngày càng ranh mãnh, hãy cảnh giác !"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/18047-bon-bat-coc-tre-em-ngay-cang-ranh-manh-hay-canh-giac.html"
                   title="Bọn bắt cóc trẻ em ngày càng ranh mãnh, hãy cảnh giác !"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/18047-bon-bat-coc-tre-em-ngay-cang-ranh-manh-hay-canh-giac.html"
                       title="Bọn bắt cóc trẻ em ngày càng ranh mãnh, hãy cảnh giác !">
                        Bọn bắt cóc trẻ em ngày càng ranh mãnh, hãy cảnh giác ! </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">284,733</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/ca6388210dfcc1ae1bafe73234fa7400.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/ca6388210dfcc1ae1bafe73234fa7400.jpg"
                     title="Tết đến rồi, uống rượu bia thế nào cho... đúng cách nhé ! ;)"
                     alt="Tết đến rồi, uống rượu bia thế nào cho... đúng cách nhé ! ;)"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/17975-tet-den-roi-uong-ruou-bia-the-nao-cho-dung-cach-nhe.html"
                   title="Tết đến rồi, uống rượu bia thế nào cho... đúng cách nhé ! ;)"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/17975-tet-den-roi-uong-ruou-bia-the-nao-cho-dung-cach-nhe.html"
                       title="Tết đến rồi, uống rượu bia thế nào cho... đúng cách nhé ! ;)">
                        Tết đến rồi, uống rượu bia thế nào cho... đúng cách nhé ! ;) </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">1,061,488</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/77bf7e24a6a967af734950fbeed16746.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/77bf7e24a6a967af734950fbeed16746.jpg"
                     title="Gáiiiiiii xinh kìa AE ơi, thính nặng lắm rồi =))"
                     alt="Gáiiiiiii xinh kìa AE ơi, thính nặng lắm rồi =))"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/15701-gaiiiiiii-xinh-kia-ae-oi-thinh-nang-lam-roi.html"
                   title="Gáiiiiiii xinh kìa AE ơi, thính nặng lắm rồi =))"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/15701-gaiiiiiii-xinh-kia-ae-oi-thinh-nang-lam-roi.html"
                       title="Gáiiiiiii xinh kìa AE ơi, thính nặng lắm rồi =))">
                        Gáiiiiiii xinh kìa AE ơi, thính nặng lắm rồi =)) </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">62,897</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/bf38b7ef552b48d9d2b440ab4286588b.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/bf38b7ef552b48d9d2b440ab4286588b.jpg"
                     title="Thanh niên này bá đạo thật, yêu xong đòi quà."
                     alt="Thanh niên này bá đạo thật, yêu xong đòi quà."
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/16760-thanh-nien-nay-ba-dao-that-yeu-xong-doi-qua.html"
                   title="Thanh niên này bá đạo thật, yêu xong đòi quà."
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/16760-thanh-nien-nay-ba-dao-that-yeu-xong-doi-qua.html"
                       title="Thanh niên này bá đạo thật, yêu xong đòi quà.">
                        Thanh niên này bá đạo thật, yêu xong đòi quà. </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">339,508</span> lượt xem</p>
            </div>
        </div>
        <div class="post">
            <div class="poster"
                 style="background: url(<?php echo STATIC_URL; ?>/picture/small/6ca3fbc1bfaabe562aabc46d265fc70f.jpg) no-repeat center;">
                <img src="<?php echo STATIC_URL; ?>/picture/small/6ca3fbc1bfaabe562aabc46d265fc70f.jpg"
                     title="Soobin Hoàng Sơn song ca &quot;Phía sau một cô gái&quot; cùng cô gái Hàn Quốc ;)"
                     alt="Soobin Hoàng Sơn song ca &quot;Phía sau một cô gái&quot; cùng cô gái Hàn Quốc ;)"
                     class="thumbnail"
                />
                <div class="bg-gradient"></div>
                <a href="post/17945-soobin-hoang-son-song-ca-phia-sau-mot-co-gai-cung-co-gai-han-quoc.html"
                   title="Soobin Hoàng Sơn song ca &quot;Phía sau một cô gái&quot; cùng cô gái Hàn Quốc ;)"
                   class="link">
                </a>
            </div>
            <div class="content">
                <h3 class="title">
                    <a href="post/17945-soobin-hoang-son-song-ca-phia-sau-mot-co-gai-cung-co-gai-han-quoc.html"
                       title="Soobin Hoàng Sơn song ca &quot;Phía sau một cô gái&quot; cùng cô gái Hàn Quốc ;)">
                        Soobin Hoàng Sơn song ca &quot;Phía sau một cô gái&quot; cùng cô gái Hàn Quốc
                        ;) </a>
                </h3>
                <div class="hot">
                    <img src="<?php echo STATIC_URL; ?>/images/general/icon-hot-42x57.png"
                         alt="icon"/>
                    <p><span class="score">Độ hot 0</span></p>
                </div>
                <p class="view"><span class="number">646,545</span> lượt xem</p>
            </div>
        </div>
    </div>
</div>