<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 responsive-width-top">
                <div class="social">
                    <div class="social-icon">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-google-plus"></i></a>
                        <a href="#"><i class="fa fa-linkedin"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 responsive-width-top">
                <div class="links text-right">
                    <a href="new-ad.html">Post an Ad</a>
                    <a href="register.html">Register</a>
                    <a href="login.html">Login</a>
                </div>
            </div>
        </div>
    </div>
</div>