<style>#page {
        background-color: #e7e7e7;
    }</style>
<div id="category-page">
    <div class="container page-width">
        <div class="main-content">
            <div class="header">
                <div class="videos">
                    <?php
                    foreach ($this->arrContentList as $key => $arr_content):
                        $cont_image = json_decode($arr_content['cont_image'], true);
                        ?>
                        <div class="post"
                             style="background-image: url(<?php echo $cont_image['640x480']; ?>)">
                            <img src="<?php echo STATIC_URL; ?>/images/bg-default-740x400.gif"
                                 alt="Default Background"
                                 class="bg-default"
                            />
                            <div class="bg-gradient"></div>
                            <div class="content">
                                <h1 class="title">
                                    <?php echo $arr_content['cont_title']; ?>
                                </h1>
                                <p class="view"><span
                                        class="number"><?php echo number_format($arr_content['cont_views']); ?></span>
                                    view</p>
                            </div>
                            <a href="<?php echo $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
                               title="<?php echo $arr_content['cont_title']; ?>"
                               class="link">
                            </a>
                        </div>
                        <?php
                        if ($key == 3) {
                            break;
                        }
                    endforeach; ?>
                </div>
                <div class="navigation"></div>
            </div>
            <div class="inside-container">
                <div class="inside">
                    <h4 class="name">
                        <a><?php echo $this->arrCategoryDetail['cate_name']; ?></a>
                        <span></span>
                    </h4>
                    <div class="videos">
                        <?php
                        foreach ($this->arrContentList as $key => $arr_content):
                            if ($key <= 3) {
                                continue;
                            }
                            $cont_image = json_decode($arr_content['cont_image'], true);
                            ?>
                            <div class="post">
                                <div class="poster"
                                     style="background-image: url(<?php echo $cont_image['320x180']; ?>)">
                                    <div class="bg-gradient"></div>
                                    <p class="duration"><?php echo \My\General::formatDurationLength($arr_content['cont_duration']) ?></p>
                                    <p class="view"><span
                                            class="number"><?php echo number_format($arr_content['cont_views']); ?></span>
                                        view</p>
                                    <a href="<?php echo $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
                                       title="<?php echo $arr_content['cont_title']; ?>"
                                       class="link">
                                    </a>
                                </div>
                                <div class="content">
                                    <h3 class="title">
                                        <a href="<?php echo $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
                                           title="<?php echo $arr_content['cont_title']; ?>">
                                            <?php echo $arr_content['cont_title']; ?>
                                        </a>
                                    </h3>
                                    <p class="description">
                                        <?php echo $arr_content['cont_description']; ?>
                                    </p>
                                    <p class="created">
                                        <span class="time">
                                            <?php echo \My\General::formatDateString($arr_content['created_date']) ?>
                                        </span>
                                    </p>
                                    <!--                                    <p class="author">-->
                                    <!--                                        Đăng bởi-->
                                    <!--                                        <a href="user/441.html"-->
                                    <!--                                           title="Minh Minh"-->
                                    <!--                                           class="username">-->
                                    <!--                                            Minh Minh </a>-->
                                    <!--                                    </p>-->
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="sidebar">
            <h4 class="name">Top view in <?php echo $this->arrCategoryDetail['cate_name']; ?></h4>
            <div class="videos">
                <?php foreach ($this->arrContentHot as $arr_content):
                    $cont_image = json_decode($arr_content['cont_image'], true);
                    ?>
                    <div class="post">
                        <div class="poster"
                             style="background: url(<?php echo $cont_image['120x90']; ?>) no-repeat center;">
                            <div class="bg-gradient"></div>
                            <a href="<?php echo $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
                               title="<?php echo $arr_content['cont_title']; ?>"
                               class="link">
                            </a>
                        </div>
                        <div class="content">
                            <h3 class="title">
                                <a href="<?php echo $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
                                   title="<?php echo $arr_content['cont_title']; ?>">
                                    <?php echo $arr_content['cont_title']; ?>
                                </a>
                            </h3>
                            <p class="view">
                                <span class="number">
                                    <?php echo number_format($arr_content['cont_views']); ?>
                                </span> view
                            </p>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <?php
    echo $this->paging
    ?>
</div>