<?php
$arr_key_id = array_keys($this->arrKeywordList);
?>
<div class="content">
    <h1><?php echo $this->arrCategoryDetail['cate_name']; ?></h1>
    <?php if (!empty($this->arrCategoryDetail['cate_meta_description'])): ?>
        <div class="taxdesc">
            <p><?php echo $this->arrCategoryDetail['cate_meta_description']; ?></p>
        </div>
    <?php endif; ?>
    <?php if (!empty($this->arrCategoryChildren)): ?>
        <div class="navbar">
            <div class="title">Chuyên mục</div>
            <ul class="navigation clearfix">
                <?php foreach ($this->arrCategoryChildren as $arr_category):
                    ?>
                    <li>
                        <a href='<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $arr_category['cate_slug'], 'cateId' => $arr_category['cate_id']]) ?>'>
                            <img src="<?php echo STATIC_URL . $arr_category['cate_img_url']; ?>"/>
                            <?php echo $arr_category['cate_name']; ?>
                        </a>
                    </li>
                    <?php
                endforeach;
                ?>
            </ul>
        </div>
    <?php endif; ?>

    <div class="listview">
        <ul>
            <div id="adindexcenter" class="adbox" style="margin-bottom:20px">
                <!-- khampha content -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-9166980393030854"
                     data-ad-slot="3530466045"
                     data-ad-format="auto"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
        </ul>
        <ul>
            <?php foreach ($this->arrContentList as $key => $arr_content):
                $key_temp = $key * 2;
                ?>
                <li class="listitem clearfix">
                    <a class="title"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>">
                        <?php echo $arr_content['cont_title']; ?>
                    </a>
                    <a class="thumb"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
                       rel="nofollow">
                        <img src="<?php echo $arr_content['cont_main_image'] ?>"
                             alt="<?php echo $arr_content['cont_title'] ?>"/>
                    </a>
                    <div class="desc"><?php echo $arr_content['cont_description'] ?>
                        <?php if (in_array($key_temp, $arr_key_id)): ?>
                            <div class="link">
                                <a href="<?php echo $this->serverUrl() . $this->Url('keyword', array('keySlug' => $this->arrKeywordList[$key_temp]['key_slug'], 'keyId' => $this->arrKeywordList[$key_temp]['key_id'])) ?>"
                                   title="<?php echo $this->arrKeywordList[$key_temp]['key_name']; ?>">
                                    <?php echo $this->arrKeywordList[$key_temp]['key_name']; ?>
                                </a>,
                                <?php if (in_array($key_temp + 1, $arr_key_id)): ?>
                                    <a href="<?php echo $this->serverUrl() . $this->Url('keyword', array('keySlug' => $this->arrKeywordList[$key_temp + 1]['key_slug'], 'keyId' => $this->arrKeywordList[$key_temp + 1]['key_id'])) ?>"
                                       title="<?php echo $this->arrKeywordList[$key_temp + 1]['key_name']; ?>">
                                        <?php echo $this->arrKeywordList[$key_temp + 1]['key_name']; ?>
                                    </a>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </li>
                <?php if ($key == 2): ?>
                <div id="adindexcenter" class="adbox" style="margin-bottom:20px">
                    <!-- khampha -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-9166980393030854"
                         data-ad-slot="3530466045"
                         data-ad-format="auto"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
            <?php endif; ?>
            <?php endforeach; ?>
            <!--        </ul>-->
            <!--    </div>-->
            <!--    <div id="adindexcenter" class="adbox" style="margin-bottom:20px">-->
            <!--        <!-- KhoaHoc Cat Resp -->
            <!--    </div>-->
            <!--    <div class="listview">-->
            <!--        <ul>-->
        </ul>
    </div>
    <!--    <div id="adindexcenter" class="adbox" style="margin-bottom:20px">-->
    <!--        <!-- khampha content -->
    <!--        <ins class="adsbygoogle"-->
    <!--             style="display:inline-block;width:728px;height:90px"-->
    <!--             data-ad-client="ca-pub-4608570842050780"-->
    <!--             data-ad-slot="5752635152"></ins>-->
    <!--        <script>-->
    <!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
    <!--        </script>-->
    <!--    </div>-->
    <div class="pagination-container">
        <?php echo $this->paging; ?>
    </div>
</div>