<div class="content post-detail"
     data-url="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
     data-title="Chính sách bảo mật - Khampha.tech"
     data-load="true">
    <h1>
        <span itemprop="name">Chính sách bảo mật - Khampha.tech</span>
    </h1>
    <div class="socialbox top clearfix">
        <ul>
            <!--            <li class="raty" itemscope itemtype="http://data-vocabulary.org/Review-aggregate">-->
            <!--                <meta itemprop="itemreviewed" content="-->
            <?php //echo $this->arrContent['cont_title']; ?><!--"/>-->
            <!--                <meta itemprop="rating" content="4"/>-->
            <!--                <meta itemprop="votes" content="14"/>-->
            <!--                <span class=" rating" data-rating="4" data-id="-->
            <?php //echo $this->arrContent['cont_id']; ?><!--"></span>-->
            <!--                <span class="rating-info">4</span><span class="rating-votes">14</span>-->
            <!--            </li>-->
            <!--            <li class="views">-->
            <?php //echo number_format($this->arrContent['cont_views'] + 1, 0, ",", "."); ?><!--</li>-->
            <li class="share">
                <div class="sharebox">
                    <div class="sharetoolbox">
                        <div class="g-plusone" data-annotation="none" data-size="medium"
                             data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]); ?>"></div>

                        <div class="fb-like"
                             data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]); ?>"
                             data-layout="button_count" data-action="like" data-show-faces="false"
                             data-share="true"></div>
                        <div class="fb-like likebox" data-href="<?php echo \My\General::SOCIAL_FACEBOOK_URL; ?>"
                             data-layout="button_count" data-action="like" data-show-faces="false"
                             data-share="false"></div>
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <div class="breadcrumbs info-detail" xmlns:v="http://rdf.data-vocabulary.org/#">
        <span class="first breadcrumb">
            <a href="<?php echo BASE_URL; ?>">🏠</a>
        </span>
        <span itemprop="articleSection" typeof="v:Breadcrumb" class="breadcrumb">
            <a rel="v:url" property="v:title"
               href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id']]) ?>">
                Chính sách bảo mật
            </a>
        </span>
    </div>

    <div class="content-detail">
        <div id="adsarticletop" class="adbox">
            <!-- KhoaHoc - BaiViet - Reponsive -->
            <!--            <script>-->
            <!--                (adsbygoogle = window.adsbygoogle || []).push({});-->
            <!--            </script>-->
        </div>
        <p>Chính sách này của chúng tôi đề ra nền tảng xử lý bất kỳ thông tin và dữ liệu có thể nhận dạng cá nhân ("Dữ
            Liệu Cá Nhân") mà chúng tôi thu thập được từ bạn, hoặc bạn cung cấp cho chúng tôi. Chính sách này áp dụng
            đối với các trang web, ứng dụng, công cụ, chương trình khuyến mãi, email liên lạc, tài khoản đăng nhập và
            bất kỳ dịch vụ nào khác do chúng tôi vận hành ("Khampha.tech").</p>
        <p>Khampha.tech cam kết bảo vệ và tôn trọng quyền riêng tư của bạn và chúng tôi xem đó là ưu tiên cao nhất để
            bảo vệ tính bảo mật của bất kỳ và mọi chi tiết cá nhân mà bạn cung cấp cho chúng tôi. Là người truy cập hoặc
            người sử dụng Khampha.tech, bạn có quyền biết và hiểu về các thông lệ quyền riêng tư thông tin của chúng tôi
            trước khi cung cấp cho chúng tôi bất kỳ chi tiết cá nhân nào của bạn.</p>
        <p>Khi sử dụng Khampha.tech, bạn được xem như là đồng ý với việc chúng tôi sử dụng Dữ Liệu Cá Nhân của bạn theo
            chính sách này.</p>
        <p>Khampha.tech không nhằm dành cho trẻ em dưới 13 tuổi, và trẻ dưới 13 tuổi không phải cung cấp bất kỳ thông
            tin nào cho, trên hoặc qua Khampha.tech. Chúng tôi không cố ý thu thập Dữ Liệu Cá Nhân từ trẻ dưới 13 tuổi,
            và nếu chúng tôi biết rằng chúng tôi đã thu thập hoặc nhận được Dữ Liệu Cá Nhân từ trẻ dưới 13 tuổi, chúng
            tôi sẽ xóa thông tin đó.</p>
        <p>Chính sách của chúng tôi là đăng tải bất kỳ thay đổi nào mà chúng tôi thực hiện đối với chính sách về quyền
            riêng tư của chúng tôi trên trang này, chúng tôi đề nghị bạn thường xuyên truy cập để kiểm tra bất kỳ sự
            thay đổi nào.</p>
        <p>Chúng tôi thu thập loại thông tin nào?</p>
        <p>Chúng tôi thu thập thông tin do bạn cung cấp khi bạn đăng ký để nhận hoặc sử dụng bất kỳ dịch vụ nào của
            chúng tôi. Ví dụ như nếu bạn tạo tài khoản đăng ký với chúng tôi, giữ chỗ hoặc đặt vé du lịch trong
            Khampha.tech, tham gia chương trình khuyến mãi của Khampha.tech hoặc đăng ký để nhận 'Thông báo giá', 'Thư
            gửi bằng đường hàng không' hoặc các giao tiếp khác, chúng tôi có thể hỏi tên, địa chỉ email, chi tiết mật
            khẩu hoặc thông tin cá nhân có liên quan khác của bạn như số hộ chiếu hoặc chi tiết thanh toán.</p>
        <p>Chúng tôi tự động thu thập những thông tin nhất định một cách thụ động do việc bạn sử dụng Khampha.tech.
            Thông tin này được liên kết đến thiết bị mà bạn sử dụng để truy cập vào Khampha.tech và bao gồm địa chỉ IP,
            hệ điều hành, loại trình duyệt, URL tham khảo, xem trang, thời gian truy cập và vị trí địa lý của bạn.</p>
        <p>Chúng tôi cũng thu thập thông tin được cung cấp cho chúng tôi khi bạn kết nối với Khampha.tech từ ứng dụng
            bên thứ ba, trang mạng xã hội (như Facebook hoặc Twitter) hoặc trang web khác (như đối tác khuyến mãi).</p>
        <h2>Sử dụng thông tin</h2>
        <p>Chúng tôi sẽ sử dụng thông tin mà chúng tôi có được về bạn theo những cách thức sau đây:</p>
        <ul>
            <li>.xác minh sự cho phép của bạn để truy cập vào các tính năng nhất định;</li>
            <li>.cho phép bạn truy cập và sử dụng các dịch vụ mà bạn quyết định nhận;</li>
            <li>.tối ưu Khampha.tech và cá nhân hóa những lần truy cập của bạn bằng cách nhớ cấu hình vị trí, ngôn ngữ
                và tiền tệ cũng như các mục tìm kiếm trước;
            </li>
            <li>.nhằm mục đích quản lý hệ thống;</li>
            <li>.phân tích hành vi và xu hướng của người dùng để cải thiện và hiểu hơn về cách mọi người sử dụng dịch vụ
                của chúng tôi;
            </li>
            <li>.tạo ra các bộ thông tin không thể nhận dạng cá nhân tổng hợp để thông báo về quyết định kinh doanh và
                cấp nguồn lực cho các yếu tố của một số Khampha.tech;
            </li>
            <li>.liên lạc với bạn:</li>
            <li>-.nếu bạn yêu cầu chúng tôi làm như vậy hoặc hồi âm liên lạc mà bạn đã gửi cho chúng tôi;</li>
            <li>-.nếu cần thiết để thông báo với bạn về những thay đổi hoặc cập nhật đối với dịch vụ của chúng tôi;</li>
            <li>-.gửi xác nhận đặt vé và thông báo hoặc bản tin mà bạn đã đăng ký, bao gồm đến thiết bị di động của
                bạn;
            </li>
            <li>-.nếu bạn đã quyết định đăng ký hoặc được pháp luật cho phép, gửi email tiếp thị đến bạn từ địa chỉ
                Khampha.tech về các dịch vụ của chúng tôi hoặc của các đối tác chúng tôi. Bạn cũng có thể quyết định
                không nhận các email đó bằng cách nhấp vào đường liên kết hủy đăng ký ở cuối email đó.
            </li>
        </ul>
        <p>Như đã trình bày ở trên, bạn có thể được yêu cầu cung cấp thông tin địa chỉ, số hộ chiếu và thẻ tín dụng/ghi
            nợ hoặc thông tin thanh toán khác cho chúng tôi hoặc cho đối tác đặt vé liên quan khi bạn giữ chỗ hoặc đặt
            vé du lịch trong Khampha.tech. Trong những trường hợp mà thông tin sẽ được thu thập và được sử dụng chỉ để
            xử lý đặt vé của bạn hoặc nếu bạn đề nghị chúng tôi lưu lại nhằm mục đích tự động điền chi tiết của bạn cho
            các lần đặt vé sau này. Đôi khi trình duyệt mà bạn đang sử dụng để truy cập Khampha.tech có thể đề nghị lưu
            chi tiết thanh toán của bạn để tự động điền vào (riêng biệt với Khampha.tech). Trong những trường hợp đó,
            chi tiết thanh toán của bạn sẽ được lưu nội bộ trong thiết bị của bạn hoặc theo chính sách về quyền riêng tư
            của trình duyệt mà bạn đã chọn.</p>
        <h2>Tiết lộ thông tin của bạn</h2>
        <p>Chúng tôi sẽ không bao giờ bán Dữ Liệu Cá Nhân của bạn cho các bên thứ ba, mặc dù thỉnh thoảng chúng tôi có
            thể chia sẻ hoặc cung cấp Dữ Liệu Cá Nhân của bạn cho các bên thứ ba theo chính sách này hoặc nếu luật pháp
            yêu cầu chúng tôi làm điều này.</p>
        <p>Chúng tôi có thể chia sẻ thông tin của bạn với các bên thứ ba chọn lọc để xử lý thông tin của bạn thay mặt
            chúng tôi hoặc nếu cần để cung cấp dịch vụ mà bạn yêu cầu. Ví dụ như chúng tôi có thể tiết lộ địa chỉ email
            của bạn cho các công ty bên thứ ba tin cậy cùng với những dữ liệu khác mà chúng tôi thu thập được để giúp
            xác định khuynh hướng và tùy chỉnh Khampha.tech cũng như mọi liên lạc mà chúng tôi gửi đến bạn.</p>
        <p>Chúng tôi yêu cầu các bên thứ ba này (một số bên có thể hoạt động ngoài phạm vi EEA) tuân thủ nghiêm ngặt các
            hướng dẫn của chúng tôi và chúng tôi cũng đề nghị rằng họ không sử dụng Dữ Liệu Cá Nhân của bạn cho mục đích
            kinh doanh riêng của họ, trừ khi bạn đồng ý rõ ràng với việc sử dụng Dữ Liệu Cá Nhân của bạn theo cách này.
            Bất kỳ bên thứ ba nào truy cập dữ liệu của bạn torng khi cung cấp dịch vụ thay mặt bạn phải tuân theo các
            giới hạn nghiêm ngặt theo hợp đồng để đảm bảo rằng dữ liệu của bạn được bảo vệ, và chỉ được xử lý theo luật
            pháp bảo vệ dữ liệu/về quyền riêng tư hiện hành. Chúng tôi cũng có thể kiểm tra độc lập những nhà cung cấp
            dịch vụ này để đảm bảo rằng họ đáp ứng các tiêu chuẩn của chúng tôi.</p>
        <p>Nếu bạn đang tiến hành đặt chỗ hoặc đặt vé du lịch trong Khampha.tech, chúng tôi có thể truyền bất kỳ Dữ Liệu
            Cá Nhân nào mà bạn cung cấp cho chúng tôi đến nhà cung cấp dịch vụ du lịch cuối cùng mà bạn đang đặt chỗ
            hoặc đặt vé để sử dụng theo các điều khoản và điều kiện cũng như chính sách về quyền riêng tư của chính
            họ.</p>
        <p>Chúng tôi có thể chia sẻ thông tin của bạn với các công ty liên kết trong tập đoàn Khampha.tech để sử dụng
            theo chính sách này và nhằm mục đích được trình bày ở trên. Chúng tôi cũng có thể tiết lộ Dữ Liệu Cá Nhân
            của bạn nếu cần thiết để ngăn chặn, phát hiện hoặc khởi tố các hoạt động bất hợp pháp hoặc nghi ngờ phạm
            pháp hoặc để ngăn chặn hoặc hưởng ứng hành động pháp lý hoặc thực thi quyền và yêu cầu thanh toán của chúng
            tôi.</p>
        <p>Ngoài ra, chúng tôi cũng có thể tiết lộ Dữ Liệu Cá Nhân của bạn nếu cần để thực hiện hoặc các thỏa thuận khác
            của chúng tôi, hoặc cho người mua tương lai và người mua cuối cùng trong trường hợp chính Khampha.tech (hoặc
            một bộ phận trong doanh nghiệp của chúng tôi) được bán.</p>
        <p>Chúng tôi cũng có thể chia sẻ thông tin sử dụng ẩn danh được tổng hợp với những thông tin khác.</p>
        <h2>Lưu giữ dữ liệu</h2>
        <p>Tất cả các Dữ Liệu Cá Nhân mà bạn cung cấp cho chúng tôi được lưu giữ trong máy chủ an toàn. Hiện tại, chúng
            tôi sử dụng các máy chủ được đặt tại Liên minh Châu Âu, vùng Châu Á Thánh bình Dương và Trung Quốc; các máy
            chủ cụ thể lưu dữ liệu của bạn sẽ tùy thuộc vào địa điểm mà bạn truy cập Khampha.tech. Bất kể là địa điểm
            nào, chúng tôi cũng đảm bảo luôn có sẵn các biện pháp kỹ thuật và tổ chức đầy đủ để bảo vệ sự an toàn Dữ
            Liệu Cá Nhân của bạn. Chúng tôi giới hạn truy cập vào Dữ Liệu Cá Nhân của bạn với những nhân viên nào mà
            chúng tôi tin rằng có nhu cầu hợp pháp tiếp xúc với thông tin đó để hoàn tất vai trò của họ và để cung cấp
            sản phẩm hoặc dịch vụ cho bạn.</p>
        <p>Tiếc là việc truyền thông tin qua internet không bao giờ có thể được đảm bảo hoàn toàn. Mặc dù chúng tôi sẽ
            cố gắng bảo vệ Dữ Liệu Cá Nhân của bạn, nhưng chúng tôi không thể đảm bảo dữ liệu của bạn được truyền an
            toàn đến các trang web của chúng tôi hoặc Khampha.tech khác; bạn chịu mọi rủi ro khi truyền thông tin. Sau
            khi chúng tôi nhận được Dữ Liệu Cá Nhân của bạn, chúng tôi sẽ sử dụng các thủ tục và tính năng bảo mật
            nghiêm ngặt để cố gắng ngăn chặn trường hợp truy cập trái phép.</p>
        <p>Khampha.tech có các đường liên kết đến trang web bên thứ ba mà bạn có thể được chuyển đến. Vui lòng lưu ý
            rằng chúng tôi không chịu trách nhiệm về các thông lệ bảo vệ quyền riêng tư của các trang web bên thứ ba
            này. Chúng tôi khuyến khích bạn đọc các câu trình bày/chính sách về quyền riêng tư của từng và mỗi trang web
            bên thứ ba mà bạn liên kết từ Khampha.tech.</p>
        <p>Để đem đến cho bạn một trải nghiệm xã hội hữu ích khi sử dụng Khampha.tech, chúng tôi có thể cho bạn lựa chọn
            xuất thông tin sang các ứng dụng và trang web của bên thứ ba, bao gồm các trang mạng xã hội như Facebook
            hoặc Twitter. Khi xuất thông tin, bạn có thể đang tiết lộ thông tin của mình với các cá nhân hoặc tổ chức
            chịu trách nhiệm vận hành và duy trì các ứng dụng và các trang của bên thứ ba đó và thông tin của bạn có thể
            được người khác tiếp cận khi truy cập hoặc sử dụng các ứng dụng hoặc trang này. Chúng tôi không sở hữu hoặc
            vận hành các ứng dụng hoặc trang web mà bạn kết nối và bạn nên xem lại các chính sách về quyền riêng tư của
            các trang web đó để chắc chắn rằng bạn thoải mái với các cách mà họ sử dụng thông tin mà bạn chia sẻ với
            họ.</p>
        <h2>Truy cập vào Dữ Liệu Cá Nhân của bạn</h2>
        <p>Theo luật pháp hiện hành, bạn có quyền tìm hiểu chúng tôi giữ những Dữ Liệu Cá Nhân nào của bạn vào bất kỳ
            lúc nào. Nếu bạn muốn thực hiện đề nghị này, vui lòng gửi yêu cầu bằng văn bản đến Khampha.tech, Quartermile
            One, 15 Lauriston Place, Edinburgh EH3 9EN gửi cho 'Giám đốc bộ phận pháp lý'.</p>
        <p>Bạn có quyền đề nghị chúng tôi không xử lý Dữ Liệu Cá Nhân của bạn nhằm mục đích tiếp thị. Bạn có thể thực
            hiện quyền này bằng cách đánh dấu chọn vào các ô nhất định trong biểu mẫu mà chúng tôi sử dụng để thu thập
            dữ liệu của bạn hoặc liên lạc với chúng tôi vào bất kỳ lúc nào <a
                href="http://www.Khampha.tech.net/contactus.aspx"
                onclick="trackOutboundLink(Khampha.tech.analyticsPageName, &quot;text-link-click&quot;, &quot;5_tại đây&quot;)">tại
                đây</a>. Bạn cũng có thể quyết định không nhận bất kỳ email tiếp thị nào bằng cách nhấp vào đường liên
            kết hủy đăng ký ở cuối email đó.</p>
        <p>Nếu bạn là người sử dụng dịch vụ đăng nhập của chúng tôi, bạn có thể quản lý một số thông tin và lựa chọn cá
            nhân của bạn từ "Tài khoản" trên trang web của chúng tôi.</p>
        <h2>Liên hệ chúng tôi</h2>
        <p>Nếu bạn có bất kỳ câu hỏi nào về chính sách này, vui lòng <a href="http://www.Khampha.tech.net/contact">liên
                hệ chúng tôi</a>.</p>
        <!--        <script>-->
        <!--        // if (location.hostname.toLowerCase().indexOf("khoahoc.tv") < 0) { location.href = "http://khoahoc.tv/"; }-->
        <!--//        </script>-->
    </div>
    <div class="author-info clearfix">
        <span class="date">Cập nhật: 23/10/2016</span>
        <span class="author" style="float: right">Khampha.tech</span>
    </div>
    <!--        <div id="adsarticlebottom" class="adbox">-->
    <!--            <!-- KhoaHoc-BaiViet-Resposive -->
    <!--            <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9275417305531302"-->
    <!--                 data-ad-slot="8671917284" data-ad-format="auto"></ins>-->
    <!--            <script>-->
    <!--                (adsbygoogle = window.adsbygoogle || []).push({});-->
    <!--            </script>-->
    <!--        </div>-->
<!--    <div class="socialbox bottom clearfix">-->
<!--        <ul>-->
<!--            <li class="share">-->
<!--                <div class="sharebox">-->
<!--                    <div class="sharetoolbox">-->
<!--                        <div class="g-plusone" data-annotation="none" data-size="medium"-->
<!--                             data-href="--><?php //echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?><!--"></div>-->
<!---->
<!--                        <div class="fb-like"-->
<!--                             data-href="--><?php //echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?><!--"-->
<!--                             data-layout="button_count" data-action="like" data-show-faces="false"-->
<!--                             data-share="true"></div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </li>-->
<!--            <!--            <li class="raty">-->
<!--            <!--                <span class="rating" data-rating="4" data-id="40490"></span>-->
<!--            <!--                <span class="rating-info">4</span><span class="rating-votes">14</span>-->
<!--            <!--            </li>-->
<!--            <!--            <li class="views">-->
<!--            --><?php ////echo number_format($this->arrContent['cont_views'] + 1, 0, ",", "."); ?><!--<!--</li>-->
<!--        </ul>-->
<!--    </div>-->


<!--    <p>-->
<!--        <a href="--><?php //echo \My\General::SOCIAL_FACEBOOK_URL; ?><!--" target="_blank" rel="nofollow">Theo dõi cộng đồng-->
<!--            --><?php //echo \My\General::SITE_AUTH; ?><!-- trên-->
<!--            facebook</a>-->
<!--    </p>-->
<!--    <div class="fb-like" data-href="--><?php //echo \My\General::SOCIAL_FACEBOOK_URL; ?><!--" data-layout="standard"-->
<!--         data-action="recommend" data-show-faces="true" data-share="true"></div>-->
<!---->
<!--    <div class="comments">-->
<!--        <div id="fb_comments" class="fb-comments"-->
<!--             data-href="--><?php //echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?><!--"-->
<!--             data-num-posts="3"-->
<!--             data-width="640"></div>-->
<!--    </div>-->
    <!--    <div id="suggestion" class="adbox">-->
    <!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
    <!--        </script>-->
    <!--    </div>-->

<!--    <div class="more-news latest">-->
<!--        <div class="list-title">Bài viết mới nhất</div>-->
<!--        <ul class="clearfix">-->
<!--            --><?php //foreach ($this->arrContentNews as $arr_content): ?>
<!--                <li>-->
<!--                    <a href="--><?php //echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?><!--">-->
<!--                        <span class="thumb-detail">-->
<!--                            <img src="--><?php //echo $arr_content['cont_main_image'] ?><!--"-->
<!--                                 alt="--><?php //echo $arr_content['cont_title'] ?><!--"/>-->
<!--                        </span>-->
<!--                        <span>--><?php //echo $arr_content['cont_title'] ?><!--</span>-->
<!--                    </a>-->
<!--                </li>-->
<!--            --><?php //endforeach; ?>
<!--        </ul>-->
<!--        <a href="--><?php //echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryParent['cate_slug'], 'cateId' => $this->arrCategoryParent['cate_id']]) ?><!--"-->
<!--           class="viewmore"><b>Xem thêm</b> --><?php //echo $this->arrCategoryParent['cate_name']; ?><!--</a>-->
<!--    </div>-->

<!--    <div class="more-news">-->
<!--        <div class="list-title">Bài viết --><?php //echo $this->arrCategoryDetail['cate_name']; ?><!-- khác</div>-->
<!--        <ul class="clearfix">-->
<!--            --><?php
//            if (!empty($this->arrContentLastedList)):
//                foreach ($this->arrContentLastedList as $arr_content):
//                    ?>
<!--                    <li>-->
<!--                        <a href="--><?php //echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?><!--">-->
<!--                        <span class="thumb-detail">-->
<!--                            <img src="--><?php //echo $arr_content['cont_main_image'] ?><!--"-->
<!--                                 alt="--><?php //echo $arr_content['cont_title'] ?><!--"/>-->
<!--                        </span>-->
<!--                            <span>--><?php //echo $arr_content['cont_title'] ?><!--</span>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                --><?php //endforeach;
//            endif;
//            ?>
<!--        </ul>-->
<!--        <a href="--><?php //echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id']]) ?><!--"-->
<!--           class="viewmore">Xem thêm</a>-->
<!--    </div>-->
</div>
