<?php
$arrRole = $this->arrRole;
//print_r($arrRole);die;
?>
<section class="wrapper site-min-height">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <header class="panel-heading">
                    <button type="button" class="btn btn-success pull-right" id="btnToggleFilterUser" style="margin:-6px -11px 0 0;">Ẩn/Hiện công cụ tìm kiếm</button>
                    Danh sách người dùng
                </header>
                <div class="panel-body">
                    <div id="frmFilterUser" class="panel-body" style="<?php echo $this->isFilter ? 'display:block;' : 'display:none;' ?>;">
                        <form id="frm" class="form-horizontal" role="form" method="GET">
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <td style="width:20%;font-weight:600;">Họ và tên</td>
                                        <td>
                                            <input id="fullname" type="text" name="fullname" class="form-control" placeholder="Nhập họ và tên người dùng" value="<?php echo $this->params['user_fullname'] ? $this->params['user_fullname'] : ''; ?>">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="width:15%;font-weight:600;">Email</td>
                                        <td>
                                            <input id="email" type="text" name="email" class="form-control" placeholder="Nhập email người dùng" value="<?php echo $this->params['user_email'] ? $this->params['user_email'] : ''; ?>">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="width:20%;font-weight:600;">Số điện thoại</td>
                                        <td>
                                            <input id="phoneNumber" type="text" name="phoneNumber" class="form-control" placeholder="Nhập số điện thoại" value="<?php echo $this->params['phoneNumber'] ? $this->params['phoneNumber'] : ''; ?>">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="width:20%;font-weight:600;">Nhóm</td>
                                        <td>
                                            <select name="userRole" class="form-control">
                                                <option value="">== Tất cả ==</option>

                                                <?php foreach ($arrRole as $roleID => $role) : ?>
                                                    <option value="<?php echo $role['grou_id']; ?>" <?php echo ($this->params['userRole'] == $roleID) ? 'selected="selected"' : '' ?>><?php echo $role['grou_name'] ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <a href="<?php echo $this->serverUrl() . $this->url('backend', array('controller' => 'user', 'action' => 'index')); ?>" class="btn btn-danger">Bỏ tìm kiếm</a>
                            <button type="submit" class="btn btn-info">Tìm kiếm</button>
                        </form>
                    </div>
                </div>
                <div class="panel-body">
                    <section id="flip-scroll">
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th>Họ Và Tên</th>
                                    <th>Email</th>
                                    <th>Địa chỉ</th>
                                    <th style="text-align:center;">Số ĐT</th>
                                    <th style="text-align:center;">Nhóm</th>
                                    <th style="text-align:center;">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if ($this->arrUserList):
                                    foreach ($this->arrUserList as $arrUser):
                                        ?>
                                        <tr>
                                            <td>
                                                <a class="tooltips" data-placement="top" data-original-title="Xem thông tin người dùng" href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'user', 'action' => 'view', 'id' => $arrUser['user_id'])); ?>">
                                                    <?php echo $arrUser['user_fullname']; ?>
                                                </a>
                                            </td>
                                            <td><?php echo $arrUser['user_email']; ?> </td>
                                            <td><?php echo $arrUser['user_address']; ?> </td>
                                            <td style="text-align:center;"><?php echo $arrUser['user_phone']; ?></td>
                                            <td style="text-align:center;">
                                                <?php echo (isset($arrRole[$arrUser['grou_id']]) && $arrRole[$arrUser['grou_id']]['group_name'] != '') ? $arrRole[$arrUser['grou_id']]['grou_name'] : '' ?>
                                            </td>
                                            <td style="text-align:center;">
                                                <a href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'user', 'action' => 'edit', 'id' => $arrUser['user_id'])); ?>" class="fa fa-pencil action tooltips edit" data-placement="top" data-original-title="Sửa thông tin"></a>
                                                <?php if (isset($arrRole[$arrUser['grou_id']]) && !$arrRole[$arrUser['grou_id']]['grou_description']) : ?>
                                                    <a href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'permission', 'action' => 'grant', 'pid' => $arrUser['user_id'])); ?>" class="fa fa-lock action tooltips edit" data-placement="top" data-original-title="Phân quyền"></a>
                                                <?php endif; ?>

                                                <a  class="fa fa-times-circle tooltips action remove" data-placement="top" data-original-title="Xóa người dùng" rel="<?php echo $arrUser['user_id'] ?>"></a>
                                            </td>
                                        </tr>

                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr><td colspan="6" style="text-align:center;">Hiện tại chưa có người dùng nào.</td></tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </section>
                </div>
                <div style="padding-top: 15px;">
                    <?php echo $this->paging; ?>
                </div>
            </section>

        </div>
    </div>
</section>
<script type="text/javascript">
    User.del();
</script>