<section class="wrapper site-min-height">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <header class="panel-heading">
                    <button type="button" class="btn btn-success pull-right" id="btnToggleFilterUser" style="margin:-6px -11px 0 0;">Ẩn/Hiện công cụ tìm kiếm</button>
                    Thống kê đơn hàng thành công
                </header>
                <div class="panel-body">
                    <div id="frmFilterUser" class="panel-body" style="<?php echo $this->isFilter ? 'display:block;' : 'display:none;' ?>;">
                        <form id="frm" class="form-horizontal" role="form" method="GET">
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <td style="width:20%;font-weight:600;">Họ và tên</td>
                                        <td>
                                            <input id="fullname" type="text" name="fullname" class="form-control" placeholder="Nhập họ và tên người dùng" value="<?php echo $this->params['fullname'] ? $this->params['fullname'] : ''; ?>">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="width:15%;font-weight:600;">Email</td>
                                        <td>
                                            <input id="email" type="text" name="email" class="form-control" placeholder="Nhập email người dùng" value="<?php echo $this->params['email'] ? $this->params['email'] : ''; ?>">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="width:20%;font-weight:600;">Số điện thoại</td>
                                        <td>
                                            <input id="phoneNumber" type="text" name="phoneNumber" class="form-control" placeholder="Nhập số điện thoại" value="<?php echo $this->params['phoneNumber'] ? $this->params['phoneNumber'] : ''; ?>">
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <a href="<?php echo $this->serverUrl() . $this->url('backend', array('controller' => 'user', 'action' => 'statistic')); ?>" class="btn btn-danger">Bỏ tìm kiếm</a>
                            <button type="submit" class="btn btn-info">Tìm kiếm</button>
                        </form>
                    </div>
                </div>
                <div class="panel-body">
                    <section id="flip-scroll">
                        <p>*Tổng số tiền lãi = Tổng chi phí đơn hàng khi về VN - Tổng giá sản phẩm sau thuế tại Mỹ.</p>
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th style="text-align:center;">Họ và tên</th>
                                    <th style="text-align:center;">Email</th>
                                    <th style="text-align:center;">Số điện thoại</th>
                                    <th style="text-align:center;">Số đơn hàng</th>
                                    <th style="text-align:center;">Tổng giá SP sau thuế tại Mỹ</th>
                                    <th style="text-align:center;">Tổng số tiền lãi*</th>
                                    <th style="text-align:center;">Xem đơn hàng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if ($this->arrUserList):
                                    $serviceOrder = $this->getHelperPluginManager()->getServiceLocator()->get('My\Models\Order');
                                    foreach ($this->arrUserList as $arrUser):
                                        $userID = $arrUser['user_id'];

                                        if (isset($arrUser['total_order']) && isset($arrUser['total_estimated_fee'])) {
                                            $totalOrder = $arrUser['total_order'];
                                            $totalPurchase = $arrUser['total_estimated_fee'];
                                            $totalIncome = $arrUser['total_income'];
                                        } else {
                                            $arrCondition = array(
                                                'user_id' => $userID,
                                                'payment_status' => 6
                                            );
                                            $arrTotalOrder = $serviceOrder->getTotalPurchase($arrCondition);
                                            $totalOrder = $arrTotalOrder['total_order'];
                                            $totalPurchase = $arrTotalOrder['total_purchase'];
                                            $totalIncome = $arrTotalOrder['total_income'];
                                        }


                                        $viewOrderUrl = $this->serverUrl() . $this->Url('backend-order-search', array(
                                                    'controller' => 'order', 'action' => 'index',
                                                    'isOrderFilter' => 1,
                                                    'paymentStatus' => 6,
                                                    'orderType' => -1,
                                                    'email' => strip_tags($arrUser['email']),
                                                        )
                                        );
                                        ?>
                                        <tr>
                                            <td>
                                                <a class="tooltips" data-placement="top" data-original-title="Xem thông tin người dùng" href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'user', 'action' => 'view', 'id' => $userID)); ?>">
                                                    <?php echo $arrUser['fullname']; ?>
                                                </a>
                                            </td>
                                            <td style="text-align:center;"><?php echo $arrUser['email']; ?> </td>
                                            <td style="text-align:center;"><?php echo $arrUser['phone']; ?></td>
                                            <td style="text-align:center;"><?php echo $totalOrder; ?></td>
                                            <td style="text-align:center;">$<?php echo \My\General::formatPrice($totalPurchase); ?></td>
                                            <td style="text-align:center;">$<?php echo \My\General::formatPrice($totalIncome); ?></td>
                                            <td style="text-align:center;">
                                                <a href="<?php echo $viewOrderUrl; ?>" class="fa fa-search action tooltips viewOrder" data-placement="top" data-original-title="Xem đơn hàng"></a>
                                            </td>
                                        </tr>

                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr><td colspan="8" style="text-align:center;">Hiện tại chưa có người dùng nào.</td></tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </section>
                </div>
                <div style="padding-top: 15px;">
                    <?php echo $this->paging; ?>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    User.del();
</script>