<head>
    <style>
        .pagination > li{
            float: left;
            padding: 10px;
        }
    </style> 
    <title>Archive - <?php echo $this->title;?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="vi" />
    <meta name="robots" content="NOINDEX, FOLLOW" />
    <meta http-equiv="Expires" content="0" />
    <meta name='revisit-after' content='1 days' />
    <meta http-equiv="REFRESH" content="1200" />
    <meta property="article:author" content="<?php echo \My\General::SOCIAL_FACEBOOK_URL; ?>"/>
    <meta name="keywords" content="<?php echo \My\General::KEYWORD_DEFAULT; ?>">
    <meta name="description" content="<?php echo \My\General::DESCRIPTION_DEFAULT; ?>">
</head>
<body>
    <h1>Archive -  <?php echo $this->title; ?></h1>
    <?php
    foreach ($this->arrCategoryList as $value):
        ?>
        <a href="<?php echo $this->serverUrl() . $this->Url('category', array('cateSlug' => $value['cate_slug'], 'cateId' => $value['cate_id'])) ?>"><?php echo $value['cate_name'] ?></a><br/>
    <?php endforeach; ?>
</body>