<head>
    <title><?php echo \My\General::SITE_AUTH . '-' . \My\General::SITE_SLOGAN; ?> - Archive</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="content-language" content="vi"/>
    <meta name="robots" content="NOINDEX, FOLLOW"/>
    <meta http-equiv="Expires" content="0"/>
    <meta name='revisit-after' content='1 days'/>
    <meta http-equiv="REFRESH" content="1200"/>
    <meta property="article:author" content="<?php echo \My\General::SOCIAL_FACEBOOK_URL; ?>"/>
    <meta name="keywords" content="<?php echo \My\General::KEYWORD_DEFAULT; ?>">
    <meta name="description" content="<?php echo \My\General::DESCRIPTION_DEFAULT; ?>">
</head>
<body>
<h1>SITE MAP - <?php echo \My\General::SITE_AUTH; ?></h1>
<a href="<?php echo $this->serverUrl() . $this->Url('sitemap', array('action' => 'category')) ?>">Danh mục</a><br/>
<!--<a href="-->
<?php //echo $this->serverUrl() . $this->Url('sitemap', array('action' => 'tags')) ?><!--">Tags Sản phẩm</a></br>-->
<!--<a href="-->
<?php //echo $this->serverUrl() . $this->Url('sitemap', array('action' => 'tags-content')) ?><!--">Tags Bài viết</a></br>-->
<!--<a href="-->
<?php //echo $this->serverUrl() . $this->Url('sitemap', array('action' => 'brand')) ?><!--">Thương hiệu</a></br>-->
<!--<a href="--><?php //echo $this->serverUrl() . $this->Url('sitemap', array('action' => 'product')) ?><!--">Sản phẩm</a></br>-->
<a href="<?php echo $this->serverUrl() . $this->Url('sitemap', array('action' => 'content')) ?>">Bài viết</a><br/>
<a href="<?php echo $this->serverUrl() . $this->Url('sitemap', array('action' => 'keyword')) ?>">Keyword</a><br/>
<!--<a href="--><?php //echo $this->serverUrl() . $this->Url('sitemap', array('action' => 'other')) ?><!--">Other</a>-->
</body>