<head>
    <style>
        .pagination > li{
            float: left;
            padding: 10px;
        }
    </style> 
    <title>Archive - <?php echo $this->title;?> Trang <?php echo $this->intPage?></title>        
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="vi" />
    <!--<meta name="robots" content="INDEX, FOLLOW" />-->
    <meta http-equiv="Expires" content="0" />
    <meta name='revisit-after' content='1 days' />
    <meta http-equiv="REFRESH" content="1200" />
    <meta property="article:author" content="https://www.facebook.com/megavita.vn" />
    <meta name="keywords" content="megavita, suc khoe, lam dep, online, mua sam, truc tiep, gia re">
    <meta name="description" content="Megavita cung cấp mỹ phẩm, thực phẩm chức năng với số lượng &amp; chủng loại đa dạng nhất Việt Nam, đáp ứng trọn vẹn mọi nhu cầu về làm đẹp và sức khỏe.">
</head>
<body>
    <h1>Archive -  <?php echo $this->title; ?> Trang <?php echo $this->intPage ?></h1>
    <?php
    foreach ($this->arrData as $value):
        ?>
        <a href="<?php echo $value['url'] ?>"><?php echo $value['name'] ?></a><br/>
    <?php endforeach; ?>
    <div>
        <?php echo $this->paging; ?>
    </div>
</body>