<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title>HTML Site Map Megavita.vn</title>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <style type="text/css">
            body {
                background-color: #DDD;
                font: normal 80%  "Trebuchet MS", "Helvetica", sans-serif;
                margin:0;
                text-align:center;
            }
            #cont{
                margin:auto;
                width:800px;
                text-align:left;
            }
            a:link,a:visited {
                color: #0180AF;
                text-decoration: underline;
            }
            a:hover {
                color: #666;
            }
            h1 {
                background-color:#fff;
                padding:20px;
                color:#00AEEF;
                text-align:left;
                font-size:32px;
                margin:0px;
            }
            h3 {
                font-size:12px;
                background-color:#B8DCE9;
                margin:0px;
                padding:10px;
            }
            h3 a {
                float:right;
                font-weight:normal;
                display:block;
            }
            th {
                text-align:center;
                background-color:#00AEEF;
                color:#fff;
                padding:4px;
                font-weight:normal;
                font-size:12px;
            }
            td {
                font-size:12px;
                padding:3px;
                text-align:left;
            }
            tr {background: #fff}
            tr:nth-child(odd) {background: #f0f0f0}
            #footer {
                background-color:#B8DCE9;
                padding:10px;
            }
            .pager,.pager a {
                background-color:#00AEEF;
                color:#fff;
                padding:3px;
            }
            .lhead {
                background-color:#fff;
                padding:3px;
                font-weight:bold;
                font-size:16px;
            }
            .lpart {
                background-color:#f0f0f0;
                padding:0px;
            }
            .lpage {
                font:normal 12px verdana;
            }
            .lcount {
                background-color:#00AEEF;
                color:#fff;
                padding:2px;
                margin:2px;
                font:bold 12px verdana;
            }
            a.aemphasis {
                color:#009;
                font-weight:bold;
            }
        </style>

    </head>
    <?php
    
    $listCategory=$this -> listCategory;
    $listBrand=$this -> listBrand;
    $listProduct=$this -> listProduct;
    $listListContent=$this -> listListContent;
    $listGeneral=$this -> listGeneral;
    
    ?>
    <body>
        <div id="cont">
            <h1>HTML Site Map Megavita.vn</h1>
            <h3><a href="http://megavita.vn">Homepage</a>
                Last updated: 2015, May 26
            </h3>


            <table cellpadding="0" cellspacing="0" border="0" width="100%">

                <tr valign="top">
                    <td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    
                    <td class="lpart" colspan="<?php echo count($listBrand)?>"><div class="lhead">Thương hiệu
                            <span class="lcount"><?php echo count($listBrand) ?></span></div>

                        <table cellpadding="0" cellspacing="0" border="0" width="100%">
                            <?php foreach ($listBrand as $brand): ?>
                            <tr><td class="lpage"><a href="<?php echo $this->serverUrl() . $this->Url('brand', array('brandSlug' => $brand['cate_slug'])); ?>" title="<?php echo $brand['cate_name'] ?>"><?php echo $brand['cate_name'] ?></a></td></tr>
                        <?php endforeach; ?>
                        </table>
                    </td>
                    
                    
                </tr>

                <tr valign="top">
                    <td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td class="lpart" colspan="<?php echo count($listCategory)?>"><div class="lhead">Danh mục
                            <span class="lcount"><?php echo count($listCategory)?> pages</span></div>

                        <table cellpadding="0" cellspacing="0" border="0" width="100%">
                            <?php foreach ($listCategory as $category):
                            $str=str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', substr_count($category['cate_grade'], ":")-1);
                                ?>
                            <tr><td class="lpage"><?php echo $str; ?><a href="<?php echo $this->serverUrl() . $this->Url('category', array('categorySlug' => $category['cate_slug'],'categoryID'=>$category['cate_id']));  ?>" title="<?php echo $category['cate_name'] ?>"><?php echo $category['cate_name'] ?></a></td></tr>
                            <?php endforeach; ?>
                        </table>
                    </td>
                </tr>

                <tr valign="top">
                    <td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td class="lpart" colspan="<?php echo count($listListContent) ?>"><div class="lhead">Bài viết
                            <span class="lcount"><?php echo count($listListContent) ?> pages</span></div>

                        <table cellpadding="0" cellspacing="0" border="0" width="100%">
                            <?php foreach($listListContent as $content):?>
                            <tr><td class="lpage"><a href="<?php echo $this->serverUrl() . $this->Url('content_detail', array('contslug' => $content['cont_slug'],'contId'=>$content['cont_id']));  ?>" title="<?php echo $content['cont_title'] ?>"><?php echo $content['cont_title'] ?></a></td></tr>
                            <?php endforeach; ?>
                        </table>
                    </td>
                </tr>

                <tr valign="top">
                    <td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td class="lpart" colspan="<?php echo count($listProduct) ?>"><div class="lhead">Sản phẩm
                            <span class="lcount"><?php echo count($listProduct) ?> pages</span></div>

                        <table cellpadding="0" cellspacing="0" border="0" width="100%">
                            <?php foreach($listProduct as $product): ?>
                            <tr><td class="lpage"><a href="<?php echo $this->serverUrl() . $this->Url('product', array('productslug' => $product['prod_slug'],'productId'=>$product['prod_id']));  ?>" title="<?php echo $product['prod_name']; ?>"><?php echo $product['prod_name']; ?></a></td></tr>
                            <?php endforeach;?>
                        </table>
                    </td>
                </tr>

            </table>


            <!--
            Please note:
            You are not allowed to remove the copyright notice below.
            Thank you!
            www.xml-sitemaps.com
            -->
            <div id="footer">
                Page generated by XML-Megavita.vn - <a target="_blank" href="<?php echo $this->serverUrl().'/sitemap.xml' ?>"> XML sitemap Megavita.vn</a>
                |
                Copyright &copy; 2005-2015

            </div>
        </div>
    </body>
</html>
