<div class="content">
    <div id="adindexcenter" class="adbox" style="margin-bottom:20px">
        <!-- khampha.tech -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-9166980393030854"
             data-ad-slot="3530466045"
             data-ad-format="auto"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
    <div class="listview">
        <ul>
            <?php
            foreach ($this->arrContentList as $key => $arrContent):
                ?>
                <li class="listitem clearfix">
                    <a class="title"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]) ?>">
                        <?php echo $arrContent['cont_title']; ?>
                        <?php echo in_array($arrContent['cate_id'], \My\General::$cate_videos) ? '<img src ="' . STATIC_URL . '/f/v1/images/video_icon-sm.png" title="videos"/>' : '' ?>
                    </a>
                    <a class="thumb"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]) ?>"
                       rel="nofollow">
                        <img src="<?php echo $arrContent['cont_main_image']; ?>"
                             alt="<?php echo $arrContent['cont_title']; ?>"/>
                    </a>
                    <div
                        class="desc"><?php echo $arrContent['cont_description'] ? $arrContent['cont_description'] : $arrContent['cont_title']; ?></div>
                </li>
                <?php if ($key == 2): ?>
                <div id="adindexcenter" class="adbox" style="margin-bottom:20px">
                    <!-- khampha -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-9166980393030854"
                         data-ad-slot="3530466045"
                         data-ad-format="auto"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
            <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="pagination-container">
        <ul class="pagination">
            <?php if ($this->intPage > 1):
                if ($this->intPage == 2):?>
                    <li class="PagedList-skipToPrevious">
                        <a href="<?php echo BASE_URL; ?>" rel="prev">Quay lại</a>
                    </li>
                <?php else: ?>
                    <li class="PagedList-skipToPrevious">
                        <a href="<?php echo BASE_URL; ?>/?page=<?php echo $this->intPage - 1; ?>" rel="prev">Quay
                            lại</a>
                    </li>
                <?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($this->arrContentList)): ?>
                <li class="PagedList-skipToNext">
                    <a href="<?php echo BASE_URL; ?>/?page=<?php echo $this->intPage + 1 ?>" rel="next">Xem thêm</a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
</div>